### ISSUE TITLE
Display power/watts used on battery (and main?)

### ISSUE THREAD

**Issue by l300lvl** [paradoxxxzero/gnome-shell-system-monitor-applet#166]
A good friend gave me this idea. He uses conky and explained how using info from /sys/class/power_supply/BAT0/ for example, and I don't know exactly what would need to be done but in his conky he is doing something like:

watts used = /sys/class/power_supply/BAT1/voltage_now \* /sys/class/power_supply/BAT1/current_now

and I noticed the api seems different for me I have energy_now power_now and voltage_now

At any rate this would be an awesome addition for laptop users maybe it would even work on normal desktops somehow?

**Comment by mikey** [comment]
I use this extension to get this info https://extensions.gnome.org/extension/1501/power-indicator/
It would be nice to get it into system monitor so we could have a graph representation and not need another extension.
