### ISSUE TITLE
Wrong locale for sl

### ISSUE THREAD

**Issue by jinzo** [paradoxxxzero/gnome-shell-system-monitor-applet#167]
I just updated the applet to latest git (archlinux pkgbuild). I have the GNOME locale/language set to Slovene and this applet shows translations from some language that is not Slovene (looks like something Polish or CZ to me...). I quickly found out that the translations in "sl" folder/locale are not Slovene (and sl or sl_SI is the standard locale for Slovene afaik).

Thanks in advance,
jinzo

**Comment by marxin** [comment]
I think this is duplicate of #197, where I just created pull request.

**Comment by chrisspen** [comment]
Should be resolved along with #197.
