### ISSUE TITLE
Fan display incorrectly asks me to install lm-sensors

### ISSUE THREAD

**Issue by protist** [paradoxxxzero/gnome-shell-system-monitor-applet#169]
In in the settings window, the fan tab asks me to `Please install lm-sensors`. This is already installed, (and thermal monitoring works). I suspect the problem is that my computer is incapable of showing fan speeds, because running `$ sensors` in the command line only shows information about temperature. I suppose the error-checking and error-reporting are at fault here.

Cheers.

**Comment by AlexWayfer** [comment]
Also, package in Arch Linux is called [`lm_sensors`](https://wiki.archlinux.org/index.php/lm_sensors), not `lm-`. But I don't know how it's called in another distros.

**Comment by juanmah** [comment]
I have Arch Linux and lm_sensors installed. The problem seems to be that, by default, fan sensors are not configured.

    sudo sensors-detect

and following the instructions solved me the problem.
