### ISSUE TITLE
temporary screen freeze, video playback issues

### ISSUE THREAD

**Issue by ccrisan** [paradoxxxzero/gnome-shell-system-monitor-applet#187]
When this extension is active, the screen freezes for a short period of time (seconds at most). The problem becomes more obvious when playing a movie. The freezing seems to be correlated with the update frequency of the graphs. I noticed the same behaviour with gnome-shell 3.2, 3.4, as well as with 3.6. I noticed the issue on a machine with a GMA 4000-based video card, as well as on an older radeon X1600 video card.

**Comment by irongomme** [comment]
The same for me on OpenSuse Leap 42.2, a short 1s freeze every 3/4 s. When i desactive the extention, everything's fine !

**Comment by dtrsan** [comment]
I'm having the same issue but only when I enable CPU frequency in the menu.

**Comment by sourabh1031** [comment]
I am also having the same issue on Ubuntu 18.04 LTS

**Comment by tupm20154207** [comment]
My newly installed Ubuntu 18.04 LTS has the same issue

**Comment by return42** [comment]
>  The freezing seems to be correlated with the update frequency of the graphs.
> @dtrsan  I'm having the same issue but only when I enable CPU frequency in the menu.

The CPU freq. bug is fixed in master since PR #497 is merged. Can you please test current master and close this issue? / Thanks!

**Comment by dtrsan** [comment]
It works fine for me now. I don't have the issue anymore. Tested on Ubuntu 18.04 and 18.10.

**Comment by scporse** [comment]
I'm having issues with video playback on my Ubuntu 18.04 LTS system (stutter every 2-3 seconds), when cpu frequency stats is enabled in the system monitor applet. Can I safely fix this by upgrading to the latest release of this applet - even though I'm only on gnome 3.28.2? And if so -how would i go about doing that?
Also: Thanks for an otherwise awesome applet!

**Comment by return42** [comment]
Use the https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/tree/gnome-3.2 branch.

    sudo cp -r system-monitor@paradoxxx.zero.gmail.com /usr/share/gnome-shell/extensions

**Comment by return42** [comment]
Sorry, forget my last post .. try master branch 

    sudo cp -r system-monitor@paradoxxx.zero.gmail.com /usr/share/gnome-shell/extensions

**Comment by chrisspen** [comment]
I'm running Ubuntu 18.04 and I'm not getting any freezes.

**Comment by scporse** [comment]
> I'm running Ubuntu 18.04 and I'm not getting any freezes.

Are you also on gnome 3.28.2?

Maybe it's a hardware-specific issue...

**Comment by scporse** [comment]
> Sorry, forget my last post .. try master branch
> 
> ```
> sudo cp -r system-monitor@paradoxxx.zero.gmail.com /usr/share/gnome-shell/extensions
> ```

Is master branch equal to the version for gnome 3.30? And can i expect that to work without issues on gnome 3.28.2?
The command isn't working...

**Comment by chrisspen** [comment]
> $ gnome-shell --version
> GNOME Shell 3.28.3

**Comment by return42** [comment]
> Is master branch equal to the version for gnome 3.30? And can i expect that to work without issues on gnome 3.28.2?
The command you provided isn't working... Shouldn't it be some kind of git command instead?

OMG you see the green Button 'clone or update'?

**Comment by scporse** [comment]
> > Is master branch equal to the version for gnome 3.30? And can i expect that to work without issues on gnome 3.28.2?
> > The command you provided isn't working... Shouldn't it be some kind of git command instead?
> 
> OMG you see the green Button 'clone or update'?

I don't need that attitude from you.
I'll make do without the cpu freq stats (thus avoiding the problem) and wait for a general release which will address the bug.
