### ISSUE TITLE
Wrong translation language ID (sl/sk)

### ISSUE THREAD

**Issue by urkon** [paradoxxxzero/gnome-shell-system-monitor-applet#197]
sl language ID should be used for slovene.

Now is under sl slovak translation and it does not look cool.

Please change "po/sl","locale/sl" dir into "po/sk","locale/sk" to leave default for slovene and 
make slovak selectable for slovak setup.

**Comment by chrisspen** [comment]
Forgive my misunderstanding, but Slovak and Slovenia appear to be separate language identifiers.

https://docs.moodle.org/dev/Table_of_locales

I haven't done much translation work, so I'm not sure what the best approach here is. However, I would think removing the current "sl" translation would be a mistake. Wouldn't it be more appropriate to add an "sk" translation?

**Comment by marxin** [comment]
Yep, problem is that the texts are in Slovak (I was born in Czechslovakia) and it's wrongly described as Slovenian (sl). It's also mentioned in #197, where name of the issue mentions the same what I did ;)
