### ISSUE TITLE
displaying custom data in system-monitor

### ISSUE THREAD

**Issue by pd3** [paradoxxxzero/gnome-shell-system-monitor-applet#205]
Hello,
I'd like to reuse/extend the system-monitor to display arbitrary data supplied by a user command. I wonder how difficult it would be to tweak the code? Any advice you could offer would be greatly appreciated.
And by the way, system-monitor really rocks! Thanks for your great work! 
Petr

**Comment by p-e-w** [comment]
This and much more can be done with the [Argos](https://github.com/p-e-w/argos) extension. From my experience developing it, I can tell you that reliably running an arbitrary command at intervals without blocking is a complex task that belongs in a separate extension. Probably best to leave this feature out of system-monitor to avoid bloat.
