### ISSUE TITLE
Disk graph is empty

### ISSUE THREAD

**Issue by lvv** [paradoxxxzero/gnome-shell-system-monitor-applet#230]
I've installed from commit cc86a28 (pre 3.10 support commit), Latest 9ce5c5b - didn't worked on my Gentoo with gnome 3.8.4.  Disk graph is empty and pop-up also shows read/write - 0 MB/s.  My root partition  is on /dev/sdb1 (SSD). I have also 2nd disk - /dev/sda.  Graph remains empty even if there is IO activity on both disks.

**Comment by franglais125** [comment]
I think this is another solved issue, as of [d840030da9575f374cbf7ea35514bb801fa61d74].
