### ISSUE TITLE
High CPU utilization 

### ISSUE THREAD

**Issue by lvv** [paradoxxxzero/gnome-shell-system-monitor-applet#231]
In my i3 2.2GHz CPU, this applet uses about 8% of CPU with gnome 3.8.4.  Install was from commit cc86a28

**Comment by rzippert** [comment]
It's more like a question than an answer, but isn't that supposed to be normal? As far as I know the linux kernel switches between processes every 20 miliseconds. A 500ms update interval means that every second 40 could be used by this, which translates to 4% processor time. This app seems to rely heavily on system calls, is run over an API for gnome shell and is written on interpreted languages, which probably makes it pretty inefficient CPU wise. Again, I'm saying this more as a question than an answer, but 8% with those settings seems plausible as normal to me... Even more on an i3, which is not a particularly powerful processor.

**Comment by milesfrain** [comment]
I'm seeing fairly high CPU usage of ~40% for `/usr/bin/gnome-shell` on one of my cores with this extension.
<img src="https://user-images.githubusercontent.com/3578681/148703480-b4f65087-005d-4226-909b-328892d947b4.png" width="500">

Settings are pretty basic:
<img src="https://user-images.githubusercontent.com/3578681/148703227-d761b111-7cdc-4b14-9572-91a7613f69f2.png" width="300">

Quitting this extension drops `gnome-shell` CPU usage to close to 0%.
<img src="https://user-images.githubusercontent.com/3578681/148703513-38089ef6-d124-4ace-974f-5a376c1a1ec1.png" width="500">

```
System Load Indicator version: 0.4
Gnome version: 3.36.8
Ubuntu 20.04.3
Intel® Core™ i7-7700HQ CPU @ 2.80GHz × 8 
```
