### ISSUE TITLE
memory display is truncated

### ISSUE THREAD

**Issue by dscherger** [paradoxxxzero/gnome-shell-system-monitor-applet#233]
The memory display is

Memory       7269   /    120...       MiB

Surely there's enough room to display 5 or 6 digits for total memory.

**Comment by marxin** [comment]
I guess it should be fixed now as RAM >= 4GB is displayed as follows:

![issue-272](https://cloud.githubusercontent.com/assets/2658545/21079911/d7639e74-bfa0-11e6-87af-1c124063510d.png)

Please close if resolved.
