### ISSUE TITLE
requires alread installed lm-sensors 

### ISSUE THREAD

**Issue by ousia** [paradoxxxzero/gnome-shell-system-monitor-applet#236]
I’m using commit 9ce5c5bacd packaged for Fedora 20 and I experience a weird issue.

In preferences, the fan tab has a drop-down menu for sensors, but when I click on it, I get a message: “Please install lm-sensors”.

Well, the weird thing is that (all available packages for) lm-sensors are installed on my Fedora distribution.

What am I missing here?

Many thanks for the excellent work.

**Comment by Zemogiter** [comment]
I have the same issue. Already installed lm-sensors and sudo sensors-detect. The sensor command only shows temperatures. My motherboard is Gigabyte Z270 Gaming K3. Please help

**Comment by return42** [comment]
@Zemogiter Does the problem still exist?

**Comment by tengwar** [comment]
@return42 I can't check because lm-sensors started detecting my fan sensors. 😁

**Comment by return42** [comment]
@tengwar  if now one can observe this error anymore, I would say it is fixed.

@ousia .. if so, can you please close the issue / thanks

**Comment by tengwar** [comment]
@return42 More like "cannot reproduce" than "fixed" but yeah, I guess it can be closed until @Zemogiter answers.

**Comment by eugenio** [comment]
Is this issue fixed? I'm experiencing the same problem described here. I'm on ubuntu 18.04 and the machine is a tuxedo laptop.

**Comment by entodoays** [comment]
I'm still getting the "please install lm-sensors" error. It doesn't happen all the time. It's like a lottery: one day it works, the next it doesn't. lm-sensors is installed and shows fan speed.

**Comment by hsh9544** [comment]
I've the same problem. It was working fine, but after running `sensors-detect` it's asking to install `lm-sensors` for fan.

**Comment by krustophenia** [comment]
> I've the same problem. It was working fine, but after running `sensors-detect` it's asking to install `lm-sensors` for fan.

+1 on Fedora 35 + gnome
