### ISSUE TITLE
Wrong tooltip text placement in gnome-shell 3.10

### ISSUE THREAD

**Issue by p91paul** [paradoxxxzero/gnome-shell-system-monitor-applet#237]
The screenshot should say all. All text in drop down is misaligned!

![schermata da 2014-02-27 11 11 32](https://f.cloud.github.com/assets/2157006/2281103/8ef0000a-9f97-11e3-83a0-7d1faa7dc574.png)

**Comment by franglais125** [comment]
Long time coming, but this was fixed. Missing part is the tooltip.
