### ISSUE TITLE
Order of items changed

### ISSUE THREAD

**Issue by purpleidea** [paradoxxxzero/gnome-shell-system-monitor-applet#245]
Since Gnome 2.x days, the order was:
CPU - Memory - Net - Swap - Disk

For some reason this has now changed to:
CPU - Memory - Swap - Net - Disk

Either change this back, or make it configurable.

Thanks!

**Comment by jbonlinea** [comment]
Hi

any news on that point ? 

I also wish we could set the order of the sensors.

I do not like CPU-MEM-NETWORK-TEMP and would prefer NETWORK-MEMORY-CPU-TEMP

Thanks

**Comment by return42** [comment]
Can we mark this issue as feature request?

**Comment by purpleidea** [comment]
Sweet that @DColadas added a patch! :eyes:
