### ISSUE TITLE
tooltips are mass

### ISSUE THREAD

**Issue by pynixwang** [paradoxxxzero/gnome-shell-system-monitor-applet#246]
I disable them by comment the signal connection.

[https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/blob/master/system-monitor%40paradoxxx.zero.gmail.com/extension.js#L625-L626](https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/blob/master/system-monitor%40paradoxxx.zero.gmail.com/extension.js#L625-L626)

can I extend ElementBase without anything?

**Comment by DirkHoffmann** [comment]
Looks like this is done in master branch. (Checkbox in Preferences window.) Works with GNOME 3.16.
