### ISSUE TITLE
system-monitor keeps eating up memory

### ISSUE THREAD

**Issue by paolobenve** [paradoxxxzero/gnome-shell-system-monitor-applet#261]
System-monitor is a very useful extension, but since I installed it I began experimenting growing up memory usage.

I could see that disabling all extensions memory usage doesn't grow, nor it grows enabling all extensions but system-monitor.

Enabling system-monitor causes a continuous grow memory usage.

you can see it running in a terminal:

watch -n1 ps -p $(pidof gnome-shell) -o rss=

with my settings (I update the graphs quite often) I have an increase of 4k every second

Disabling and reenabling system-monitor doesn't free memory, you have to restart gnome-shell

**Comment by chrisspen** [comment]
I can't reproduce this problem. Please re-open if this is still occurring.
