### ISSUE TITLE
Menu almost empty

### ISSUE THREAD

**Issue by NVieville** [paradoxxxzero/gnome-shell-system-monitor-applet#268]
Hello,

Last version (ccafeef) show an almost empty menu on Fedora 20. All the items are there, but no values are shown and updated regularly. The only values displayed are CPU and Network bitrates. Memory, swap, hard disk drive io, etc. items show only empty values.

Hope this description will be enough to catch this issue. 

Cordially,

-- 
NVieville

**Comment by darkxst** [comment]
This was probably fixed in #267

**Comment by NVieville** [comment]
You are right. This is fixed in the last commit (6b9973e).

Thank you very much.

Cordially,


-- 
NVieville
