### ISSUE TITLE
GTop (any version) not found.

### ISSUE THREAD

**Issue by BLXCryptor** [paradoxxxzero/gnome-shell-system-monitor-applet#27]
Hi,

I have been trying to get this to work for Fedora 15, however I am getting the following error:

error ... While loading extension from ... : Error: Requiring Gtop, version none: Typelib file for namespace 'GTop' (any version) not found.

I am certain that I have something missing from my system and I did try to install all GTop available in the fedora Repos, however I will still available to resolve this..

Do you think you can give me some advice?

Thank!

**Comment by mastier** [comment]
In Ubuntu it's better to install the required package and just create symlink
```
$ sudo apt install gir1.2-gtop-2.0
```
```
sudo ln -s /usr/lib/x86_64-linux-gnu/girepository-1.0 /usr/lib64/
```
Then you will have this lib always up-to-date
