### ISSUE TITLE
Text color in GNOME 3.16

### ISSUE THREAD

**Issue by DreaminginCodeZH** [paradoxxxzero/gnome-shell-system-monitor-applet#272]
In GNOME 3.16, default shell theme is set to Adwaita-like, so the background of Popup menu is kind of grey instead of black, making the text hard to read.

Can you make text color #fff (with secondary text color #eee)?

**Comment by DirkHoffmann** [comment]
I checked out from git today and ran it with Adwaita theme on GNOME 3.16. It looks very good, and text is readable. 
Maybe this ticket can be closed? (Or requester should specify where exactly text color should be changed.)

**Comment by AlexSartori** [comment]
+1, this is what it looks like

![image](https://cloud.githubusercontent.com/assets/9355579/16625456/f414e9b0-43a4-11e6-99ae-fb43cad2fae9.png)
