### ISSUE TITLE
.sm-tooltip-box is defined twice in stylesheet.css

### ISSUE THREAD

**Issue by zhanghai** [paradoxxxzero/gnome-shell-system-monitor-applet#273]
In [line 75](https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/blob/master/system-monitor%40paradoxxx.zero.gmail.com/stylesheet.css#L75) and [line 178](https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/blob/master/system-monitor%40paradoxxx.zero.gmail.com/stylesheet.css#L178).

Maybe you mean `.sm-tooltp-box-compact` for the latter one, according to the context?

**Comment by chrisspen** [comment]
Good catch. Both classes have identical contents. Not sure what original author had in mind. It might just be a typo or it might have been the start of a *-compact version. I've removed the duplicate.
