### ISSUE TITLE
breaks alt-tab on Ubuntu Gnome 14.04.2

### ISSUE THREAD

**Issue by halfmanhalffish** [paradoxxxzero/gnome-shell-system-monitor-applet#274]
I installed version 31 of system monitor on Ubuntu Gnome 14.04.2 and then found that alt-tab would no longer advance the selection past the second icon in its list.  The <Super>-tab switcher still worked however.
Uninstalling system monitor fixed the problem.
There were no apparent related errors in .xsession-errors, Xorg.0.log or syslog.
I'm happy to help with debugging this if you want.

**Comment by chrisspen** [comment]
Are you still encountering this problem on the most recent release? I also use the alt-tab extension, and I haven't noticed any problems in either Ubuntu 14.04 or 16.04.

**Comment by halfmanhalffish** [comment]
I have a new box now ( Ubuntu 16.04.1 LTS 64-bit )  and a new version of
gnome without system monitor.  But I've just now gone and installed system
monitor
( https://extensions.gnome.org/extension/120/system-monitor/ )
and it works and doesn't manifest the alt tab problem.
