### ISSUE TITLE
Text is not aligned with the panel

### ISSUE THREAD

**Issue by sudhirkhanger** [paradoxxxzero/gnome-shell-system-monitor-applet#275]
The temperature text is not aligned in the Y-axis.

![screenshot from 2015-05-13 19 23 08](https://cloud.githubusercontent.com/assets/841656/7620053/ab7e548a-f9da-11e4-82bd-93cf5ed7a836.png)

**Comment by Ecron** [comment]
I can confirm this still happens in GNOME 3.24.0, both in the widget and the tooltip.

![captura de pantalla de 2017-04-06 20-33-18](https://cloud.githubusercontent.com/assets/488803/24769888/5d5ef7e0-1b08-11e7-8d13-06860ef74772.png)

**Comment by hackel** [comment]
In my case, it is particularly noticeable, especially with the Openweather extension showing the temperature right next to it.
![image](https://cloud.githubusercontent.com/assets/583677/26080936/4c6f9396-398e-11e7-8023-b3f77f6e44f8.png)

**Comment by franglais125** [comment]
Hey, here is a tentative fix: https://github.com/franglais125/gnome-shell-system-monitor-applet/tree/text_alignment_topbar

I'll try to make it better later on.

**Comment by hackel** [comment]
@franglais125 This worked for me to centre the temp, but the font is still tiny.  I don't mind it that way, myself.

Curious why you changed the character displayed for the units?
```
-        return this.fahrenheit_unit ? '\u2109' : '\u2103';
+        return this.fahrenheit_unit ? ' \u00B0F' : ' \u00B0C';
```
On my system, they produce Oriya characters:
    00B0F = ଏ
    00B0C = ଌ
Unless I am misunderstanding something.

**Comment by franglais125** [comment]
@hackel thanks for the quick feedback!

I was actually working on this right now...

1. As for the tiny fonts: are you using the option "Compact Display"?
2. Regarding the symbols, that's weird... It looks much nicer on my system with the new symbols. I took the unicode characters from the openweather extension. What Locale do you use? And thanks for reporting this!

**Comment by franglais125** [comment]
I reverted the change of symbols :)

**Comment by hackel** [comment]
@franglais125 Yes, I did have Compact Display enabled.  Disabling it didn't seem to change anything, though.

Regarding the characters, I only noticed by accident when I was browsing the source code and was curious.  I'm using UTF-8, and just looked up the characters in the GNOME Characters app.  I never actually saw those characters in the UI, though.
