### ISSUE TITLE
Allow memory stats to be displayed in GB

### ISSUE THREAD

**Issue by mrthehud** [paradoxxxzero/gnome-shell-system-monitor-applet#279]
Instead of seeing that I have 15494 MiB of ram, I'd like to be able to see "16.5 GiB" by selecting either "GiB" or "Ideal" (Uses appropriate unit to keep value between 0 and 1023) from a "Unit" dropdown on the memory tab in the preferences panel.

Or is this possible already using dconf or some other tool?

aside: I think Ubuntu switched to using SI data units for data, eg MB (10^6) instead of MiB (2^20) a few years ago, so is it (or can it be) possible to tell the whole applet to use either SI or Binary units?

**Comment by marxin** [comment]
I guess this issue can be closed as the pull request was merged.
