### ISSUE TITLE
JS LOG: error reading: /sys/devices/virtual/thermal/cooling_device0/cur_state

### ISSUE THREAD

**Issue by fthiery** [paradoxxxzero/gnome-shell-system-monitor-applet#282]
Using Arch, it seems that the extension is defaulting on trying to read /sys/devices/virtual/thermal/cooling_device0/cur_state which does not exist (but cooling_device1-14 do exist. 

It looks to be related to the fan-sensor-file gsettings key, but i tried to force it using:

```
$ gsettings set org.gnome.shell.extensions.system-monitor fan-sensor-file "/sys/devices/virtual/thermal/cooling_device1/cur_state"
$ No such schema 'org.gnome.shell.extensions.system-monitor'
```

I don't really understand why that wouldn't work, any tip appreciated.

Also, when trying to select another fan through the settings, i was advised to install lm-sensors, but 1) lm-sensors is not available on Arch anymore and 2) looking at the code, it doesn't really look related to lm-sensors itself directly.

My current workaround was to patch the org.gnome.shell.extensions.system-monitor.gschema.xml file to look into cooling_device1 instead of cooling_device0 and then recompile:

```
    <key name="fan-sensor-file" type="s">
      <default>'/sys/devices/virtual/thermal/cooling_device1/cur_state'</default>
      <summary>Sensor File</summary>
      <description>Location of the sensor file for fan</description>
    </key>
```

```
glib-compile-schemas /usr/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/schemas
```

I think it would be best to check for  the availability of the file before trying it instead of continuously try to read it (filling system logs).

**Comment by HinTak** [comment]
Actually it seems to be have gotten worse - acpi -V acpi -V has statted mal-functioning with kernel 4.3.x (from 4.2.x) on fedora, and I see that under
/sys/devices/virtual/
I do not have "thermal" any more.
