### ISSUE TITLE
Gnome 3.17 support

### ISSUE THREAD

**Issue by porjo** [paradoxxxzero/gnome-shell-system-monitor-applet#284]
I'm using Fedora 23 beta which ships with with Gnome 3.17. System monitor is no longer working :(

**Comment by ousia** [comment]
@porjo, as suggested by commit 61ba3652c69e6e15285cfef4b6b4af08b3f68dee, I guess you should add "3.18" in `metadata.json`.

I have just made a merge request with that tiny change.

**Comment by porjo** [comment]
@ousia I actually tried that shortly after I created the issue. I added `3.17` to the `metadata.json` file e.g.
```
.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/metadata.json
```
And restarted gnome shell....but no change. Not sure about Gnome 3.18 + Fedora 23 ...is that coming later?

**Comment by darkxst** [comment]
@porjo for development releases of gnome-shell you must use the full version number i.e. 3.17.92 or whatever you have installed.

**Comment by porjo** [comment]
@darkxst thanks, that worked!
