### ISSUE TITLE
Gnome 3.18 support

### ISSUE THREAD

**Issue by porjo** [paradoxxxzero/gnome-shell-system-monitor-applet#288]
The extension mostly works by adding `3.18` to `metadata.json` (as per #285) unfortunately the info popup does not display properly when clicking on the graphs - screenshot:

![system_screen](https://cloud.githubusercontent.com/assets/1296987/10157251/b8d385d4-66cb-11e5-8e9d-206975007790.jpg)

**Comment by p91paul** [comment]
Can you test https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/pull/286?

**Comment by porjo** [comment]
Works for me, thanks!

**Comment by DreaminginCodeZH** [comment]
Could you upload the new version to GNOME Extensions site? I've just upgraded to 3.18 and hit this issue. Thanks!
