### ISSUE TITLE
Update extension for Gnome 3.18

### ISSUE THREAD

**Issue by SvetlinZarev** [paradoxxxzero/gnome-shell-system-monitor-applet#289]
Currently the extension is listed as "outdated" in gnome 3.18

**Comment by develop7** [comment]
@paradoxxxzero can you publish e.g.o's review URL?

**Comment by develop7** [comment]
@paradoxxxzero looks like an 3.18 update wasn't actually submitted — [last one enables extension for 3.16](https://extensions.gnome.org/review/4351). Can you fix that?

**Comment by danjde** [comment]
Hi friends,
confirm that on GNOME Shell 3.18.5 the last system-monitor release is listed on gnome tweak tool too) outdated.

Many thanks!

**Comment by chrisspen** [comment]
This should now be resolved by #335.
