### ISSUE TITLE
Wrong text alignment in gnome 3.18

### ISSUE THREAD

**Issue by marxin** [paradoxxxzero/gnome-shell-system-monitor-applet#290]
Hello.

I've just updated to master revision (which supports gnome 3.18). However, I see wrongly aligned text, please take a look at screenshot.

Thanks
![gnome-monitor-font-issue](https://cloud.githubusercontent.com/assets/2658545/10579483/9b5149bc-7678-11e5-93b1-92218fd5a8a0.png)

**Comment by auipga** [comment]
+1

**Comment by aalexgabi** [comment]
Same issue with the latest master version: 8b31f070e9e59109d729661ced313d6a63e31787

**Comment by aalexgabi** [comment]
I confirm that @marxin pull request fixes the issue:
![image](https://cloud.githubusercontent.com/assets/600821/19000648/f17e78be-8743-11e6-92c1-fc5d32e13fe4.png)
