### ISSUE TITLE
Mounted Webdav when system-monitor enabled slows the system down.

### ISSUE THREAD

**Issue by matejak** [paradoxxxzero/gnome-shell-system-monitor-applet#291]
When I connect to a WebDav share using Nautilus (e.g. Owncloud files) and the system-monitor is running, the system becomes almost unusable - the user interface becomes somehow unresponsive. Specifically, it "freezes" for about a half of a second every two seconds. Animations, cursor movement, everything is affected and the system becomes very unpleasant to work with.
Disabling the extension fixes this.

**Comment by p91paul** [comment]
If you want to keep the extension running, you could try disabling the monitoring of disk IO performance. This seems to be the same issue of #263.

**Comment by matejak** [comment]
How do I disable disk monitoring? I guess it is not possible to do it using the settings menu, since nothing I did there (unticking the display checkboxes + extending the monitoring period) had any impact on the problem.
On the other hand, I have tried the current git and the problem is gone!

**Comment by p91paul** [comment]
you should also remove "display in menu" to completely disable disk monitoring (at least, it should, depends how old your version was), but good to know that latest code works!
