### ISSUE TITLE
gnome extensions website says OUTDATED

### ISSUE THREAD

**Issue by vasekch** [paradoxxxzero/gnome-shell-system-monitor-applet#293]
After updating from Gnome Ubuntu 15.04 to 15.10 extension is disabled due to incompatibility.

![screenshot](https://cloud.githubusercontent.com/assets/2572537/11166089/a6c79c8a-8b25-11e5-927e-606450c36fab.png)

When trying OneClick install via web https://extensions.gnome.org/extension/120/system-monitor/
it says extension is OUTDATED

![screenshot](https://cloud.githubusercontent.com/assets/2572537/11166079/4b8aabaa-8b25-11e5-9cc0-190b0dbaa64e.png)

my version

    $ gnome-shell --version
    GNOME Shell 3.16.4

**Comment by FrankS101** [comment]
Have you tried to install the dependencies? 
libgtop and gir bindings
    on Ubuntu: gir1.2-gtop-2.0, gir1.2-networkmanager-1.0
    on Fedora: libgtop2-devel, NetworkManager-glib-devel

**Comment by vasekch** [comment]
No, I haven't, but it's seems to be already in place

```
# dpkg -l
ii  gir1.2-networkmanager-1.0:amd64                             1.0.4-0ubuntu5.1                           amd64        GObject introspection data for NetworkManager
ii  gir1.2-gtop-2.0                                             2.30.0.is.2.30.0-0ubuntu1                  amd64        gtop system monitoring library (gir bindings)
```

**Comment by vmendez-es** [comment]
The problem here is in the file named: metadata.json

Try this:
```
cd ~/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/
```

and edit the metadata.json

search for the shell version and add yours:
```
"shell-version": [
    "3.4",
    "3.6",
    "3.8",
    "3.10",
    "3.12",
    "3.14",
    "3.16" <--------This is my gnome-shell version
  ],
```
Then save the file and use Alt+F2, and type 'r' in order to restart gnome-shell.

Et voilá!

**Comment by vasekch** [comment]
Works like a charm, many thanks!

Unfortunately I don't have any clue how to integrate this solution into project, so closing this issue.

**Comment by DidierLoiseau** [comment]
I'm also affected and in the end I installed the extension manually.

The problem is that the author must publish a new version on extensions.gnome.org, because the last version still says "only compatible until 3.14" -- even if the sources were already updated.

See https://extensions.gnome.org/review/4351

I don't think this issue should be closed before the new version is published.

**Comment by vasekch** [comment]
@DidierLoiseau Ok, agreed, reopening...

**Comment by erihe251** [comment]
I installed from the git repo and my metadata.json already contains shell-version 3.18.

Although it still doesn't work for me on Fedora 23, with the dependencies.

**Comment by DidierLoiseau** [comment]
@erihe251 this issue only concerns the installation through extensions.gnome.org, it looks like you have a different issue.

**Comment by erihe251** [comment]
@DidierLoiseau Thanks, yes, it was misreading of your earlier post on my part.

**Comment by vasekch** [comment]
symptoms does not occure any more, closing

from user reviews on extensions.gnome.org:

> davey4979x
> 
> Additional notes on Fedora 23 install: (1) Do the manual install as your normal user, not root (2) After doing the manual install and restarting, go to extensions.gnome.org and click "Installed extensions", then click the "On" switch for "system-monitor".
