### ISSUE TITLE
Enhancement: Disk I/O usage only shows stats for /

### ISSUE THREAD

**Issue by gtristan** [paradoxxxzero/gnome-shell-system-monitor-applet#297]
I have encrypted root with a few volumes, the system monitor only allows showing the disk I/O for my root file system, would be great if I could configure this to show other volumes as well !

**Comment by darkxst** [comment]
it should show all volumes reported by the glib VolumeMonitor, and a handful of hardcoded fallbacks. Since unfortunately that only really reports user mounted volumes

**Comment by gtristan** [comment]
I see, indeed the disk usage also fails to find my other volumes.

However gnome-system-monitor does find them on the other hand...

**Comment by darkxst** [comment]
I think it would be good to parse the mount list from mtab, to get the system mounts. Patches welcome

**Comment by gtristan** [comment]
It looks like gnome-system-monitor, in disks.cpp is using glibtop_get_mountlist().

And looks like there is commented code in the applet which does the same, looks like this was just a case of out-of-sync language bindings ?

**Comment by darkxst** [comment]
There was a reason why we ported to Glib Volume Monitor, but its been a long time since, and can't really 100% say why. perhaps is was to do with the lack of async api in libgtop. shell extensions run in the main thread so block everything if they are slow...
