### ISSUE TITLE
CPU Frequency graph does not update

### ISSUE THREAD

**Issue by gtristan** [paradoxxxzero/gnome-shell-system-monitor-applet#298]
To make this work, system monitor extension requires a simple one-line patch:

```
    _apply: function() {
        let value = this.freq.toString();
        this.text_items[0].text = value + ' ';
+        this.vals[0] = value;
        this.tip_vals[0] = value;
        this.menu_items[3].text = value;
    },
```

I.e. just need to update the this.vals variable in _apply()

**Comment by wheatgrass** [comment]
More specifically, this line should be inserted into extension.js at line number 1430. I can confirm that this change causes the frequency graph to work.

**Comment by franglais125** [comment]
Thanks for the fix, I didn't know it was broken. I included it in https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/pull/375.
