### ISSUE TITLE
Update to Gnome 3.20 

### ISSUE THREAD

**Issue by ZhengshuaiPENG** [paradoxxxzero/gnome-shell-system-monitor-applet#304]
Thanks for your amazing work for this extension and I love it.
After I updated to Gnome 3.20 today, this extension doesn't work.
So could you make some improvement with this amazing extension?

**Comment by phcerdan** [comment]
+1

**Comment by HarlemSquirrel** [comment]
It's working for me now. Follow the instructions on the README to clone the repo and create the sym link. If you already have the repo cloned, just `cd` into that folder, run `git pull`, and restart GNOME with Alt + F2, type 'r', press enter. 

https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/pull/302

**Comment by phcerdan** [comment]
Thanks @HarlemSquirrel . It worked for me.

**Comment by porjo** [comment]
@darkxst please push a new version to https://extensions.gnome.org/

**Comment by chrisspen** [comment]
This should now be resolved by #335.
