### ISSUE TITLE
OpenSuse Leap

### ISSUE THREAD

**Issue by jitka** [paradoxxxzero/gnome-shell-system-monitor-applet#305]
I am using openSUSE_Leap_42.1 which Gnome shell  3.16.4
It wasn't possible to instal it by https://extensions.gnome.org/extension/120/system-monitor/ 
 -> it runs installation but did'n sucesfully finish
So I tried manual installation:
 # zypper install gnome-shell-devel libgtop-devel libgtop-2_0-10
 then steps from readme
Exstension is working after those steps. It would by nice if automatic installation works.

**Comment by cbcoutinho** [comment]
These steps worked for me as well, I'm going to add these steps to README.md

**Comment by chrisspen** [comment]
@jitka Make sure you install the system requirements as noted by @cbcoutinho in the README before installing. Please let me know if that doesn't work.
