### ISSUE TITLE
Can't install on UbuntuGNOME 16.04 with GNOME 3.20

### ISSUE THREAD

**Issue by cdysthe** [paradoxxxzero/gnome-shell-system-monitor-applet#311]
Hi,

Trying to install on UbuntuGNOME 16.04 with GNOME 3.20 (I stand corrected :) ) . I have all dependencies in place. The extension appears to be installed, but isn't. This is the output of journalctl -f including a restart of GNOME after install on the extension:

christian@CD-Thinkpad:~$ journalctl -f
-- Logs begin at Mon 2016-07-11 22:11:32 EDT. --
Jul 12 09:52:18 CD-Thinkpad wpa_supplicant[1041]: wlp3s0: CTRL-EVENT-CONNECTED - Connection to 04:18:d6:d1:54:80 completed [id=0 id_str=]
Jul 12 09:52:18 CD-Thinkpad NetworkManager[764]: <info>  [1468331538.7582] device (wlp3s0): supplicant interface state: 4-way handshake -> completed
Jul 12 09:53:05 CD-Thinkpad org.gnome.Shell.desktop[9596]: (gnome-shell:9596): GLib-GObject-WARNING *_: /build/glib2.0-7IO_Yw/glib2.0-2.48.1/./gobject/gsignal.c:2635: instance '0x465b360' has no handler with id '1'
Jul 12 09:53:07 CD-Thinkpad org.gnome.Shell.desktop[9596]: (gnome-shell:9596): librsvg-WARNING *_: CSS parsing error
Jul 12 09:53:07 CD-Thinkpad org.gnome.Shell.desktop[9596]: (gnome-shell:9596): librsvg-WARNING *_: CSS parsing error
Jul 12 09:53:07 CD-Thinkpad org.gnome.Shell.desktop[9596]: (gnome-shell:9596): librsvg-WARNING *_: CSS parsing error
Jul 12 09:53:07 CD-Thinkpad org.gnome.Shell.desktop[9596]: (gnome-shell:9596): librsvg-WARNING *_: CSS parsing error
Jul 12 09:53:21 CD-Thinkpad org.gnome.Shell.desktop[9596]: (gnome-shell:9596): St-WARNING *_: Ignoring length property that isn't a number at line 708, col 24
Jul 12 09:53:21 CD-Thinkpad org.gnome.Shell.desktop[9596]: (gnome-shell:9596): St-WARNING *_: Ignoring length property that isn't a number at line 708, col 24
Jul 12 09:53:26 CD-Thinkpad org.gtk.vfs.Daemon[9455]: *_ (process:12056): WARNING *_: Couldn't create directory monitor on smb://x-gnome-default-workgroup/. Error: The specified location is not mounted
Jul 12 09:53:53 CD-Thinkpad org.gnome.Shell.desktop[9596]: (gnome-shell:9596): librsvg-WARNING *_: CSS parsing error
Jul 12 09:53:53 CD-Thinkpad org.gnome.Shell.desktop[9596]: (gnome-shell:9596): librsvg-WARNING *_: CSS parsing error
Jul 12 09:53:53 CD-Thinkpad org.gnome.Shell.desktop[9596]: (gnome-shell:9596): librsvg-WARNING *_: CSS parsing error
Jul 12 09:53:53 CD-Thinkpad org.gnome.Shell.desktop[9596]: (gnome-shell:9596): librsvg-WARNING *_: CSS parsing error
Jul 12 09:54:07 CD-Thinkpad org.gnome.Shell.desktop[9596]: Window manager warning: CurrentTime used to choose focus window; focus window may not be correct.
Jul 12 09:54:07 CD-Thinkpad polkitd(authority=local)[897]: Unregistered Authentication Agent for unix-session:11 (system bus name :1.402, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8) (disconnected from bus)
Jul 12 09:54:08 CD-Thinkpad /usr/lib/gdm3/gdm-x-session[9442]: (II) intel(0): resizing framebuffer to 4160x1440
Jul 12 09:54:08 CD-Thinkpad /usr/lib/gdm3/gdm-x-session[9442]: (II) intel(0): switch to mode 1600x900@60.0 on eDP1 using pipe 1, position (2560, 0), rotation normal, reflection none
Jul 12 09:54:08 CD-Thinkpad org.gnome.Shell.desktop[9596]: current session already has an ibus-daemon.
Jul 12 09:54:08 CD-Thinkpad polkitd(authority=local)[897]: Registered Authentication Agent for unix-session:11 (system bus name :1.407 [/usr/bin/gnome-shell], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
Jul 12 09:54:09 CD-Thinkpad org.gnome.Shell.desktop[9596]: Gjs-Message: JS LOG: No permission to trigger offline updates: Polkit.Error: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: Action org.freedesktop.packagekit.trigger-offline-update is not registered
Jul 12 09:54:09 CD-Thinkpad org.gnome.Shell.desktop[9596]: Gjs-Message: JS LOG: loading user theme: /usr/share//themes/Arc-Dark-Grey/gnome-shell/gnome-shell.css
Jul 12 09:54:09 CD-Thinkpad org.gnome.Shell.desktop[9596]: (gnome-shell:9596): St-WARNING *_: length values must specify a unit
Jul 12 09:54:09 CD-Thinkpad org.gnome.Shell.desktop[9596]: (gnome-shell:9596): St-WARNING *_: length values must specify a unit
Jul 12 09:54:09 CD-Thinkpad org.gnome.Shell.desktop[9596]: (gnome-shell:9596): St-WARNING *_: length values must specify a unit
Jul 12 09:54:09 CD-Thinkpad org.gnome.Shell.desktop[9596]: (gnome-shell:9596): St-WARNING *_: length values must specify a unit
Jul 12 09:54:09 CD-Thinkpad org.gnome.Shell.desktop[9596]: (gnome-shell:9596): St-WARNING *_: Ignoring length property that isn't a number at line 708, col 24
Jul 12 09:54:11 CD-Thinkpad gnome-shell[9596]: GNOME Shell started at Tue Jul 12 2016 09:54:09 GMT-0400 (EDT)

**Comment by p91paul** [comment]
I assume you mean 3.20 :)
However, damn it, those logs don't include anything that looks useful. Could you try repeating the sequence, but running journalctl -f as root instead? it usually shows more information.

**Comment by cdysthe** [comment]
Of course I mean 3.20 :)  Anyhow, this is output of journalctl -f as root while trying to install the extensions from the web and then restart GNOME:

journalctl -f
-- Logs begin at Fri 2016-08-05 13:40:45 EDT. --
Aug 05 22:35:01 cd-yoga3pro CRON[28581]: (root) CMD ([ -x /usr/sbin/dma ] && /usr/sbin/dma -q1)
Aug 05 22:35:01 cd-yoga3pro CRON[28580]: pam_unix(cron:session): session closed for user root
Aug 05 22:38:09 cd-yoga3pro smbd[28662]: pam_unix(samba:session): session closed for user nobody
Aug 05 22:39:26 cd-yoga3pro org.gnome.Shell.desktop[3795]: (gnome-shell:3795): GLib-GObject-WARNING **: /build/glib2.0-7IO_Yw/glib2.0-2.48.1/./gobject/gsignal.c:2635: instance '0x2a7e640' has no handler with id '1'
Aug 05 22:39:38 cd-yoga3pro sudo[28724]: christian : TTY=pts/2 ; PWD=/home/christian ; USER=root ; COMMAND=/bin/su
Aug 05 22:39:38 cd-yoga3pro sudo[28724]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 05 22:39:38 cd-yoga3pro su[28725]: Successful su for root by root
Aug 05 22:39:38 cd-yoga3pro su[28725]: + /dev/pts/2 root:root
Aug 05 22:39:38 cd-yoga3pro su[28725]: pam_unix(su:session): session opened for user root by (uid=0)
Aug 05 22:39:38 cd-yoga3pro su[28725]: pam_systemd(su:session): Cannot create session: Already running in a session
Aug 05 22:39:52 cd-yoga3pro gnome-settings-daemon.desktop[3915]: (gnome-settings-daemon:3915): color-plugin-WARNING **: failed to connect to device: Failed to connect to missing device /org/freedesktop/ColorManager/devices/cups_HP_Envy_4500
Aug 05 22:39:52 cd-yoga3pro gnome-settings-daemon.desktop[3915]: (gnome-settings-daemon:3915): color-plugin-WARNING **: failed to connect to device: Failed to connect to missing device /org/freedesktop/ColorManager/devices/cups_MF8500C
Aug 05 22:39:52 cd-yoga3pro gnome-settings-daemon.desktop[3427]: (gnome-settings-daemon:3427): color-plugin-WARNING **: failed to connect to device: Failed to connect to missing device /org/freedesktop/ColorManager/devices/cups_HP_Envy_4500
Aug 05 22:39:52 cd-yoga3pro gnome-settings-daemon.desktop[3427]: (gnome-settings-daemon:3427): color-plugin-WARNING **: failed to connect to device: Failed to connect to missing device /org/freedesktop/ColorManager/devices/cups_MF8500C
Aug 05 22:40:01 cd-yoga3pro CRON[28752]: pam_unix(cron:session): session opened for user root by (uid=0)
Aug 05 22:40:01 cd-yoga3pro CRON[28753]: (root) CMD ([ -x /usr/sbin/dma ] && /usr/sbin/dma -q1)
Aug 05 22:40:01 cd-yoga3pro CRON[28752]: pam_unix(cron:session): session closed for user root
Aug 05 22:40:14 cd-yoga3pro org.gnome.Shell.desktop[3795]: Window manager warning: CurrentTime used to choose focus window; focus window may not be correct.
Aug 05 22:40:14 cd-yoga3pro polkitd(authority=local)[2886]: Unregistered Authentication Agent for unix-session:1 (system bus name :1.64, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8) (disconnected from bus)
Aug 05 22:40:15 cd-yoga3pro org.gnome.Shell.desktop[3795]: current session already has an ibus-daemon.
Aug 05 22:40:15 cd-yoga3pro polkitd(authority=local)[2886]: Registered Authentication Agent for unix-session:1 (system bus name :1.859 [/usr/bin/gnome-shell], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
Aug 05 22:40:15 cd-yoga3pro dbus[2721]: [system] Activating service name='org.freedesktop.PackageKit' (using servicehelper)
Aug 05 22:40:15 cd-yoga3pro org.gnome.Shell.desktop[3795]: Gjs-Message: JS LOG: No permission to trigger offline updates: Polkit.Error: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: Action org.freedesktop.packagekit.trigger-offline-update is not registered
Aug 05 22:40:15 cd-yoga3pro org.gnome.Shell.desktop[3795]: Gjs-Message: JS LOG: loading user theme: /usr/share//themes/Arc/gnome-shell/gnome-shell.css
Aug 05 22:40:15 cd-yoga3pro AptDaemon[28789]: INFO: Initializing daemon
Aug 05 22:40:15 cd-yoga3pro org.freedesktop.PackageKit[2721]: 22:40:15 AptDaemon [INFO]: Initializing daemon
Aug 05 22:40:15 cd-yoga3pro AptDaemon.PackageKit[28789]: INFO: Initializing PackageKit compat layer
Aug 05 22:40:15 cd-yoga3pro org.freedesktop.PackageKit[2721]: /usr/lib/python3/dist-packages/aptdaemon/worker/pkworker.py:35: PyGIWarning: PackageKitGlib was imported without specifying a version first. Use gi.require_version('PackageKitGlib', '1.0') before import to ensure that the right version gets loaded.
Aug 05 22:40:15 cd-yoga3pro org.freedesktop.PackageKit[2721]:   from gi.repository import PackageKitGlib as pk
Aug 05 22:40:15 cd-yoga3pro org.freedesktop.PackageKit[2721]: 22:40:15 AptDaemon.PackageKit [INFO]: Initializing PackageKit compat layer
Aug 05 22:40:15 cd-yoga3pro dbus[2721]: [system] Successfully activated service 'org.freedesktop.PackageKit'
Aug 05 22:40:15 cd-yoga3pro org.gnome.Shell.desktop[3795]: (gnome-shell:3795): St-WARNING **: length values must specify a unit
Aug 05 22:40:15 cd-yoga3pro org.gnome.Shell.desktop[3795]: (gnome-shell:3795): St-WARNING **: length values must specify a unit
Aug 05 22:40:15 cd-yoga3pro org.gnome.Shell.desktop[3795]: (gnome-shell:3795): St-WARNING **: length values must specify a unit
Aug 05 22:40:15 cd-yoga3pro org.gnome.Shell.desktop[3795]: (gnome-shell:3795): St-WARNING **: length values must specify a unit
Aug 05 22:40:15 cd-yoga3pro org.gnome.Shell.desktop[3795]: (gnome-shell:3795): St-WARNING **: Ignoring length property that isn't a number at line 708, col 24
Aug 05 22:40:15 cd-yoga3pro bluetoothd[2784]: Failed to set mode: Blocked through rfkill (0x12)
Aug 05 22:40:16 cd-yoga3pro gnome-shell[3795]: GNOME Shell started at Fri Aug 05 2016 22:40:15 GMT-0400 (EDT)

**Comment by chrisspen** [comment]
This should now be resolved by #335.
