### ISSUE TITLE
No version in metadata.json

### ISSUE THREAD

**Issue by franglais125** [paradoxxxzero/gnome-shell-system-monitor-applet#323]
@chrisspen since you took over maintenance, I was checking what version I was running to better trace bugs between versions/commits, but no such information is available!

Here is the last review of the extension: https://extensions.gnome.org/review/4351 (v 30). It would be nice to have the version field in the metadata.json as well.

As an example, Dash-to-dock sets the version to the latest commit when installing manually (with a Makefile, https://github.com/micheleg/dash-to-dock) so that one knows exactly the state of the extension, for bug reporting purposes.
The Makefile also produces a zip file to upload to extensions.gnome.org when one wishes to upload a new version.

I can prepare this if you are interested.

**Comment by chrisspen** [comment]
I agree, version should explicitly be in the code.

Are you aware of any formal documentation for the format of metadata.json? Google just finds me [this](https://wiki.gnome.org/Projects/GnomeShell/Extensions), which doesn't explicitly mention any formal way of documenting extension version.

A few extensions seem to simply add it under the key "version". Do you see any problem with that?

**Comment by franglais125** [comment]
Exactly. I uploaded my own extension (apt-update-indicator), and simply adding "version" worked perfectly.

I will prepare a PR with the Makefile!

**Comment by chrisspen** [comment]
Thanks.

Although I'm curious, in the link you posted, it shows this version attribute is already there, but it doesn't appear to have ever been committed. The comment "Generated by SweetTooth, do not edit" implies this was added automatically, but in this case, where is the version being tracked if it's no where in the code?

I'm assuming SweetTooth refers to [this](https://wiki.gnome.org/Projects/GnomeShell/SweetTooth), but I can't find any documentation as to where this tool pulls the version number from. Is it an auto-incrementing ID incremented on every upload to gnome.org?

**Comment by franglais125** [comment]
My guess is as good as yours:

Perhaps, as there is no "version" field, "SweetTooth" automatically checks for existing versions of a given extension, and just increments the version.

I never saw this for my extension!

**Comment by franglais125** [comment]
Here you go:
https://github.com/franglais125/gnome-shell-system-monitor-applet/tree/proper_versioning

It worked fine for me, but some testing would be nice just to be sure.

**How does it work?**
 - Run "make install" to install
 - Run "make zip-file VERSION=31" to create a zip file with the specified version number, ready to upload

**Comment by chrisspen** [comment]
Thanks. That looks good. Could you make a PR?

**Comment by franglais125** [comment]
Done!
https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/pull/326

**Comment by p91paul** [comment]
@chrisspen @franglais125 the version property, if missing in metadata.json, is automatically added and incremented by extensions.gnome.org on uploads. I don't know what the site does if the version is there, I suspect it ignores it entirely. Btw, I'm really happy to see this extension has a maintainer again, thanks @chrisspen for stepping up!

**Comment by franglais125** [comment]
@p91paul I was proposing this purely to ease the maintenance. Even though e.o.g. can handle automatically the version numbering, I've noticed that a lot of people install this extension manually, due to incompatibilities etc (which might get better now thanks to @chrisspen ). This leads to bug reports with people stating "extension doesn't because _example_".

Including the makefile provides an easy way to get a standardized installation (eog is plagued with people stating "can't install it"), with a version numbering that includes either the version, or the exact commit hash. For a given bug report, we can then ask the person to provide the version number and we can pinpoint exactly what code is being run, and hopefully identify the problem more easily.

Anyway, just my point of view.

**Comment by darkxst** [comment]
I suspect e.g.o will overwrite the version field if it exists, so it probably doesnt hurt if its there, but also you want to make sure its correct!

**Comment by franglais125** [comment]
@darkxst Indeed! I always check what the latest version is before uploading a new one (for another extension)... And then keep a tag on github as well, with the version number. (I took this scheme from dash-to-dock actually).

Anyway, the Makefile can be used to produce the zipfile ready to upload: (just repeating myself for clarity)
`make zip-file VERSION=31`
takes care of that :)

**Comment by darkxst** [comment]
@franglais125 sounds good.

**Comment by p91paul** [comment]
@franglais125 my comment was just to answer @chrisspen curiosity about how the version number appeared automagically without it being present in code :)
