### ISSUE TITLE
@chrisspen is not listed as an author in the README

### ISSUE THREAD

**Issue by Aaronik** [paradoxxxzero/gnome-shell-system-monitor-applet#324]
@chrisspen, I can't tell you how appreciative I am to see that you've taken control of this, and even if just for the interim, given this repo some of the love it deserves. Like you say, this is the best gnome extension, and it's been languishing for too long. You're doing a really good thing investing your time and energy here, and I'm sure I can speak for the thousands of people who use this that we are appreciative as hell! So good on you dude.

Oh yeah and your name isn't on the README in the authors section, which is the excuse I used to write this thank you :D

**Comment by chrisspen** [comment]
I appreciate the thought, but I'm just a maintainer. I haven't authored any original code here, and I don't claim to be an expert on writing shell extensions, so I wouldn't feel right including myself. I just use this extension heavily, and want to make sure it stays current.

**Comment by Aaronik** [comment]
Haha aight right man :)
