### ISSUE TITLE
Cant install on Fedora 25

### ISSUE THREAD

**Issue by bernardoaraujor** [paradoxxxzero/gnome-shell-system-monitor-applet#334]
I have a fresh Fedora 25 install.
Running GNOME 3.22.2.
Already installed dependencies with
`sudo yum install --assumeyes libgtop2-devel NetworkManager-glib-devel`

Extension doesn't show up when I search for it at https://extensions.gnome.org/
When I just paste https://extensions.gnome.org/extension/120/system-monitor/ to firefox and hit the ON button, nothing happens.

**Comment by ruurtjan** [comment]
Same issue here. What fixed it for me was doing the [manual install](https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet#manual-install) as described in the readme.md.

**Comment by franglais125** [comment]
@bernardoaraujor @ruurtjan 
Forgot to comment here. A new version was uploaded to e.g.o. Can you test again?

**Comment by ruurtjan** [comment]
I have since changed my setup, so I'm afraid it wouldn't prove anything if I install the new version.

**Comment by chrisspen** [comment]
Then we have to assume this is fixed. Please re-comment if you're still experiencing any problem.
