### ISSUE TITLE
Deploy current master in extensions.gnome.org

### ISSUE THREAD

**Issue by kitingChris** [paradoxxxzero/gnome-shell-system-monitor-applet#335]
Hey, just tested manually installed master branch on my ubuntu 16.10 with GNOME Shell 3.20.4.

Works well. So perhaps a good idea to deploy on extensions.gnome.org ?

**Comment by pfez** [comment]
I just tried it out installing manually on Debian stretch with Gnome shell 3.22.2 and it works too!

**Comment by chrisspen** [comment]
I've uploaded a new version to EGO.

https://extensions.gnome.org/extension/120/system-monitor/

**Comment by franglais125** [comment]
The extension is now available through e.g.o. @kitingChris you can perhaps close this issue now!
