### ISSUE TITLE
"Releases" section is inconsistant with e.g.o.

### ISSUE THREAD

**Issue by franglais125** [paradoxxxzero/gnome-shell-system-monitor-applet#337]
@chrisspen thanks for the new upload on e.g.o!

Currently, when navigating to https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/releases a few releases/tags are available, but they do not correspond to what is available through e.g.o.

How can we fix this?

**Comment by chrisspen** [comment]
I'm not sure if it makes sense to keep maintaining those. There hasn't been a new tag in over 2 years and you're the first person to request one. Do you personally have a need to install from a tag instead of master or the official release on e.g.o?

**Comment by franglais125** [comment]
Not at all, I was suggesting this as book-keeping only. I usually just install master anyway.

The use-case I was thinking of is somebody reporting an issue and saying "v32 broke for me". Then you can redirect them to the "releases" page and suggest a previous version.

Feel free to close this.

**Comment by p91paul** [comment]
I want to point out a reason to tag your repository. As an extension maintainer, I've been contacted once from a guy who created an AUR package for my extension. He told me that they usually track upstream releases (which I wasn't providing at that time), so tagging might actually help people who want to package your extension in various Linux distributions to know there is something new to be released downstream.

**Comment by franglais125** [comment]
Indeed, I forgot about that too.

Version tracking is never a bad idea IMO.

**Comment by chrisspen** [comment]
I've added a formal github release and updated the docs to explicitly mention the need for this.
