### ISSUE TITLE
Please add Catalan tranlsation file

### ISSUE THREAD

**Issue by Ecron** [paradoxxxzero/gnome-shell-system-monitor-applet#353]
The PO file is already in the "po" folder, you just need to convert it to a MO file add it to /locale/ca/.

It's been translated for so long, but the Catalan translation is not shipped with the package 😞 

Cheers.

**Comment by chrisspen** [comment]
I'm not familiar with how Gnome Shell extensions install translation files. I see there are compile.sh and merge.sh scripts, but they appear to require arguments, and there's no documentation on how they're used. Google's not finding much documentation either. Does anyone know how to proceed?

**Comment by franglais125** [comment]
Hi, I updated the translation files.

You can find them in this commit [583312dcdd23959a9cede8e55ba29cc28a74ffdf].

@chrisspen to update them (when there is a string update), you have to go to the `po/` directory and run:

```
cd po/
./compile.sh ../system-monitor@paradoxxx.zero.gmail.com/locale
```

This will update the `locale/*` subdirectories!

**Comment by franglais125** [comment]
@Ecron would you mind testing this branch https://github.com/franglais125/gnome-shell-system-monitor-applet/? I've opened a PR, but it would be nice to have confirmation that it's working before merging this.

**Comment by chrisspen** [comment]
@franglais125 Thanks for clarifying. Updating the translation files should be part of the build process in the makefile, so it's done automatically.

**Comment by franglais125** [comment]
Agreed, I'll fix that later today and send you a PR.

**Comment by chrisspen** [comment]
@franglais125 Should the `merge.sh` script be included in `update-translation`? It looks like that's used to update `po/system-monitor.pot`.

**Comment by franglais125** [comment]
I don't think it's necessary from the Makefile point of view. People using the Makefile either want to:

1) install the extension
2) build it to get a zip file

The merge part is more useful for each one of the translators, but not for users/maintainers.

### Future?
For the future, it would be nice to add a helper for translators (this is done e.g. in dash-to-dock) to more easily update the translation files. I can work on this (and then, yes, I'll add the merge.sh to the Makefile), but I don't know if it's worth it, seeing as we are in 'maintenance mode'.

For instance, in dash-to-dock running `make mergepo` will update all the relevant `*po` files with the new/changed strings in the code, so they are very easy to spot to update the translations.

However, I don't think we are seeing that many string changes. What do you think?

**Comment by Ecron** [comment]
@franglais125 There are some strings not translated, but I don't know why:

![captura de pantalla de 2017-04-06 19-07-01](https://cloud.githubusercontent.com/assets/488803/24768266/46ef7940-1b02-11e7-9b8c-3bf835e250d0.png)

**Comment by franglais125** [comment]
Well, that's annoying. However, I don't think it's about the translations being wrong. We might have to look into how the translation initialization is happening.

@Ecron (or anyone) can you confirm if this happens with other languages?

CPU, Memory, Swap, etc. are not translated. They all correspond to `ElementBase` instances.

**Comment by Ecron** [comment]
Is there any way to change system-monitor's language without changing the whole system's language?

**Comment by franglais125** [comment]
@Ecron I pushed a new commit which I think fixes the issue. Can you try again?

**Comment by Ecron** [comment]
@franglais125 I confirm, that commit fixed the issue, congratulations!!

But, in the picture I sent, shouldn't the units be placed just next to the numbers? Right now it seems they are "right aligned" instead of "left aligned", if you know what I mean...

**Comment by franglais125** [comment]
@Ecron one thing at a time ;)

I don't know if that was reported before. If not, can you open a new issue?

@chrisspen As for the Makefile, maybe we can move that discussion to the PR, which now includes the a new commit to fix the string initialization for some parts.

**Comment by Ecron** [comment]
@franglais125 I didn't find any issue similar to this (only one old issue when the text wasn't aligned at all, #237). I'll create a new one :+1:

**Comment by Ecron** [comment]
So, is this language thing already solved? Can we close this issue?

**Comment by franglais125** [comment]
If the master branch works for you, then yes, you can close this issue. At some point a new version will be uploaded to e.g.o with the fixes. Thanks!

**Comment by Ecron** [comment]
Amazing, thanks, guys! 💪
