### ISSUE TITLE
Unit texts are not aligned correctly after numerical values.

### ISSUE THREAD

**Issue by Ecron** [paradoxxxzero/gnome-shell-system-monitor-applet#355]
When clicking over the widget, the units shown after the numbers are not correctly aligned after the numerical values, as shown in the picture below (texts in Catalan):

![Screenshot](https://cloud.githubusercontent.com/assets/488803/24768266/46ef7940-1b02-11e7-9b8c-3bf835e250d0.png)

I guess the final result should be something like the following **mockup**:

![a](https://cloud.githubusercontent.com/assets/488803/24770863/b7d0d1a0-1b0b-11e7-8ffa-de2c96e324a8.png)

In this mockup, I also aligned the single-valued parameters to the first left column.

Is there any way to fix this layout?

**Comment by franglais125** [comment]
Hey, thanks for opening this. So I fixed this in the link [1], but not exactly in the same way you are proposing.

Anyway, from your screenshot and mine (to be uploaded soon), I am not sure it looks much better, it looks a bit crowded. I won't open a PR for this. Instead I'll wait for more feedback. As I said, I'm not sure it looks better.

Thoughts anyone?

[1] https://github.com/franglais125/gnome-shell-system-monitor-applet/tree/align_units

**Comment by Ecron** [comment]
In my opinion, that's a nice improvement, that's basically what I was asking for. I don't feel it more crowded, but more understandable, now every unit is next to its numerical value :+1:

In my mockup I aligned single-valued parameters to the first column, but that's just because I didn't understand why there's so much blank space between, for example, `CPU` and `7%`, or `Thermal` and `49ºC`.

**Comment by DevDef** [comment]
Definitely better!

**Comment by franglais125** [comment]
@Ecron do you mind posting a screenshot of the result with your patch?

**Comment by Ecron** [comment]
Here it is:

![captura de pantalla de 2017-05-18 12-41-34](https://cloud.githubusercontent.com/assets/488803/26198722/6f4ed9a4-3bc7-11e7-9e75-4b3f5577501f.png)

**Comment by franglais125** [comment]
Sure! It looks better in my opinion.

Moltes gracies!

**Comment by franglais125** [comment]
@ecron (and everyone), what do you think o this mockup?

I added the percentage value for Memory and Swap, hence it looks more harmonised.

![screenshot from 2017-05-18 19-21-14](https://cloud.githubusercontent.com/assets/19195975/26227256/34692b9a-3bff-11e7-927c-acf118b5cdc9.png)

**Comment by DevDef** [comment]
That’s even better. :-)

**Comment by Ecron** [comment]
@franglais125 Yep, that's even a better implementation. It both gives extra and useful info and makes the UI cleaner. +1 for your addition :+1:

Could you tell us when the update with this new addition hits the Extensions site? I didn't wanted to update because I would lose my modification, but with yours, I can update freely 😄

**Comment by franglais125** [comment]
Sounds good! Thanks for the feedback @Ecron and @DevDef , I'll include this in the other PR I have opened. Cheers!

**Comment by franglais125** [comment]
This was fixed in https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/pull/375.

Thanks again for your input :).

**Comment by Ecron** [comment]
You're very welcome :wink:
