### ISSUE TITLE
GiB is not gettextized

### ISSUE THREAD

**Issue by DevDef** [paradoxxxzero/gnome-shell-system-monitor-applet#359]
Although MiB, KiB are gettextized and hence translated, the “GiB”, “kbps” and “'Mbps” strings remain in English (BTW, the [official abbreviations](https://en.wikipedia.org/wiki/Bit_rate) for bit rates are “kbit/s” and “'Mbit/s”, so they should be changed accordingly).

TIA,

Davy

**Comment by franglais125** [comment]
Thanks for noticing this.

I added a fix in the localization PR I had already started ([e9ea188f85c6e48d26f66056bc0ee371b80b8858] in https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/pull/354)

**Comment by DevDef** [comment]
Nice. Did you mean that gettextizing “GiB” string is just the first step?
I hope you’ll also replace “kbps” and “'Mbps” by “kbit/s” and “'Mbit/s”, or at least gettextized them.
The best, IMHO, would be to do both the replacement and the gettextization…
