### ISSUE TITLE
ReferenceError: GTop is undefined

### ISSUE THREAD

**Issue by jwhipp** [paradoxxxzero/gnome-shell-system-monitor-applet#361]
In Ubuntu 17.04, I am seeing this error even though the dependencies are installed:

Reading package lists... Done
Building dependency tree       
Reading state information... Done
gir1.2-gtop-2.0 is already the newest version (2.34.2-1).
gir1.2-networkmanager-1.0 is already the newest version (1.4.4-1ubuntu3).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.

Anything else might be missing?

**Comment by franglais125** [comment]
I think this was fixed in master. Can you try installing the latest version from git? You can download, `make && make install`, and restart the session.

**Comment by jwhipp** [comment]
I removed the package and rolled the master version as instructed and we're running now.

**Comment by franglais125** [comment]
Awesome. At some point a new version will be uploaded to e.g.o. Do you mind closing the issue if *master* fixed it for you?

**Comment by jwhipp** [comment]
Thanks for the help, love the extension.  Needed something as a Unity -> Gnome convert. :+1:
