### ISSUE TITLE
Unable to open Preferences dialog

### ISSUE THREAD

**Issue by islemaster** [paradoxxxzero/gnome-shell-system-monitor-applet#362]
I receive the following error when trying to open the Preferences dialog after a [manual install](https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet#manual-install) of 0caafa1 on Ubuntu 17.04 / Gnome Shell 3.24.

![screenshot from 2017-04-17 12-09-33](https://cloud.githubusercontent.com/assets/1615761/25100954/1de3516c-2367-11e7-968d-bc6cd58d5f6f.png)

```
Error: Requiring Clutter, version none: Typelib file for namespace 'Clutter' (any version) not found

Stack trace:
  @/home/brad/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/prefs.js:5:7
  Application<._getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:74:13
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:89:31
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:243:17
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:399:5
  @<main>:1:49
```

**Comment by islemaster** [comment]
Installing package [`gir1.2-clutter-1.0`](http://packages.ubuntu.com/zesty/gir1.2-clutter-1.0) solved the problem for me.  Perhaps this should be listed with other system dependencies in the readme?

**Comment by franglais125** [comment]
@islemaster thanks for reporting and solving this. If I may ask: how did you install your system?

Did you install Ubuntu GNOME, or did you install regular Ubuntu and did something like `apt install gnome-shell` ?

**Comment by islemaster** [comment]
@franglais125 The latter - I had a vanilla Ubuntu install (Unity 7 by default) and installed `gnome-shell` manually after the 17.04 upgrade because the Unity update [broke some tray icons](https://bugs.launchpad.net/ubuntu/+source/unity/+bug/1679528).

**Comment by franglais125** [comment]
I see. I am not a Ubuntu user, but I believe that perhaps this is due to not installing the proper meta-package. You probably should have installed something like `ubuntu-gnome-meta`. @jbicha is this correct?

Anyway, I am not sure this is this extension's fault, as the fact that the gir package is missing would prevent you from accessing *any* extensions preference.

**Comment by franglais125** [comment]
@jbicha I'll file a Ubuntu bug later (sorry, not much time now). However, I'm still not sure of its validity. The only thing I can think of is making the gir package a dependency of `gnome-shell` (or something like this).

**Comment by islemaster** [comment]
It's an implicit dependency that, as a _very_ new Gnome user, I didn't understand.  I'd already installed a couple of other extensions ([TopIcons Plus](https://extensions.gnome.org/extension/1031/topicons/) and [Status Area Horizontal Spacing](https://extensions.gnome.org/extension/355/status-area-horizontal-spacing/)) via extensions.gnome.org without issue so I didn't suspect that I'd missed something.  Maybe this discussion is enough documentation for others trying to install to Gnome-on-vanilla-Ubuntu :woman_shrugging:?

**Comment by franglais125** [comment]
I understand the frustration, but again, installing `gnome-shell` is simply not the way to get the full desktop on ubuntu. I read that on a couple of blogs, and it's simply wrong and incomplete, IMO.

The appropriate way is to install `ubuntu-gnome-desktop`.

**Comment by franglais125** [comment]
Hmm, or you might be right. After all, `gnome-shell-extensions` depends on that package!

**Comment by islemaster** [comment]
You are right, my install is definitely not officially supported - at least from looking at the [Getting GNOME page](https://www.gnome.org/getting-gnome/) it looks like Ubuntu GNOME is the only official Ubuntu+GNOME combination.

**Comment by chrisspen** [comment]
I've updated the readme to note that package.
