### ISSUE TITLE
Bugfix: GTop is not defined

### ISSUE THREAD

**Issue by allestuetsmerweh** [paradoxxxzero/gnome-shell-system-monitor-applet#366]
As I read from the comments [here](https://extensions.gnome.org/extension/120/system-monitor/), I am not the only one experiencing this problem since ~April 20...

The only thing that I can tell is that the extension fails with Error `ReferenceError: GTop is not defined`. (Alt+F2, then select "Extensions", and at the "system-monitor" entry, click "Show Errors")

**Comment by franglais125** [comment]
This is a duplicate of #341, it is already fixed in the master branch, and was uploaded to e.g.o. It is pending review.

If you want to install it on 3.24, you can use the master branch:
```
git clone https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet
cd gnome-shell-system-monitor-applet
make && make install
```

**Comment by allestuetsmerweh** [comment]
Uff sorry, I thought this issue only existed since ~April 20, so I wasn't looking at older issues.

**Comment by franglais125** [comment]
No worries :). I just hope it's working for you now!
