### ISSUE TITLE
RAM over RAM size

### ISSUE THREAD

**Issue by rugk** [paradoxxxzero/gnome-shell-system-monitor-applet#378]
Although the graph shows otherwise the RAM is nearly full in the text description. (see image)
Also it was about 7.72 GiB before, so it showed more RAM than available was used while no swap is shown. This was quite strange…

![ramsize](https://cloud.githubusercontent.com/assets/11966684/26576559/957d7908-4529-11e7-86c2-95638840cdf2.png)

Fedora 25

**Comment by franglais125** [comment]
I'd be happy o look into this, but I don't understand what happened.

What I see on the image seems to be consistent: the RAM (green) graph is not being used too much, and the text show that as well.

Something else happened but you couldn't get it in the screenshot?

**Comment by rugk** [comment]
Mhh, now I see it too… 
I know I made this screenshot too late and previously the RAM usage was higher, but… I could also interpreted the "2" as a seven there… 🤦

So I better close this issue.😌
