### ISSUE TITLE
Can't install on Ubuntu Gnome 17.04

### ISSUE THREAD

**Issue by Altiano** [paradoxxxzero/gnome-shell-system-monitor-applet#379]
![screenshot from 2017-06-11 19-59-04](https://user-images.githubusercontent.com/8316282/27010831-9cb2ebd4-4ee0-11e7-8228-98a02516bb53.png)

**Comment by Altiano** [comment]
![screenshot from 2017-06-11 20-01-53](https://user-images.githubusercontent.com/8316282/27010849-d884e05e-4ee0-11e7-9d2c-bbb7cdabc957.png)

**Comment by franglais125** [comment]
As far as I can tell, you are not looking for the right package.

From this site's README:
```
sudo apt-get install gir1.2-gtop-2.0 gir1.2-networkmanager-1.0 gir1.2-clutter-1.0
```

You were looking for `libgtop`, which is not the same!

**Comment by chrisspen** [comment]
The error message you received told you exactly what to do. You're running Ubuntu, so you should install the Ubuntu packages, as @franglais125 as outlined. It looks like you tried to install the Arch packages, which is incorrect.

**Comment by Altiano** [comment]
So sorry, I didn't read that...
