### ISSUE TITLE
How to specify my preferences via command line

### ISSUE THREAD

**Issue by Jadamso** [paradoxxxzero/gnome-shell-system-monitor-applet#382]
For example, what terminal code could I enter to specify showing all cpu cores?

**Comment by franglais125** [comment]
You can use the following command:

```
dconf write /org/gnome/shell/extensions/system-monitor/cpu-individual-cores true
```

Note that you'll have to restart the Shell for the changes to take effect.

**Comment by Jadamso** [comment]
Thank you
