### ISSUE TITLE
Tooltips shown outside of the screen when toolbar placed at the bottom

### ISSUE THREAD

**Issue by xvik** [paradoxxxzero/gnome-shell-system-monitor-applet#408]
I am using [dash to panel](https://extensions.gnome.org/extension/1160/dash-to-panel/) extension which creates windows like bottom toolbar instead of usual toolbars. 

When "show tooltip" option is enabled, tooltips are shown at the bottom of the graph which is outside of the screen:
![sysind_bug](https://user-images.githubusercontent.com/999676/32133634-954710d0-bc06-11e7-9dcc-071e7c90e9bc.png)
(you can see it below CPU chart (1px gray line))

Ubuntu 17.10
Arc shell theme (applied with [User themes](https://extensions.gnome.org/extension/19/user-themes/) extension)

**Comment by piegamesde** [comment]
I can confirm the issue. Here is how it looks when you have two monitors:

![screenshot from 2018-02-01 00-17-56](https://user-images.githubusercontent.com/14054505/35652884-e67f391c-06e5-11e8-93d6-84e34792c448.png)

**Comment by piegamesde** [comment]
@xvik Please have a look at my repository to test if it resolves the issue for you (it should though).

**Comment by franglais125** [comment]
Fixed in [9627c3906488dcbd803d19b57523f058a1baedc6].
