### ISSUE TITLE
The gnome-shell process (v3.26.1) uses 30%+ with this app

### ISSUE THREAD

**Issue by stumpc5** [paradoxxxzero/gnome-shell-system-monitor-applet#411]
As I wrote in https://askubuntu.com/a/973810/620569, it seems that this app uses 30%+ cpu on ``gnome-shell 3.26.1`` when I use a refresh time of below 1000 ms. Can you confirm this issue / is this expected behaviour?

**Comment by franglais125** [comment]
This is not the expected behavior, but also I cannot reproduce this. Using `500ms` for CPU, RAM and Net, my gnome-shell cpu usage is roughly `7%`, on a weak mobile cpu (intel i5 2450m).

1. What do you use as the time interval when set below `1000ms`? 
2. Can you share the output the following command?
`dconf dump /org/gnome/shell/extensions/system-monitor/`

**Comment by stumpc5** [comment]
Long story short: I cannot reproduce the problem anymore either, at least to the extend I wrote. Even without the extension, the ``gnome-shell`` process went down from 8-10% to ~2% cpu (I played a lot with the installation since I observed this about a week ago). I will report back in case I reproduce it again. Anyway, thanks for the quick reply!

Here is the ``dconf dump``, even if it is not worth anything currently:
```
$  dconf dump /org/gnome/shell/extensions/system-monitor/
[/]
net-refresh-time=500
cpu-style='graph'
battery-show-text=false
swap-meter=false
compact-display=true
load-meter=true
move-clock=false
position='right'
center-display=false
net-show-text=true
show-tooltip=true
network-meter=true
memory-meter=false
fan-show-menu=false
net-style='graph'
fan-display=false
memory-display=false
storage-meter=false
thermal-show-text=false
cpu-individual-cores=false
swap-show-menu=false
icon-display=false
memory-refresh-time=100
fan-show-text=false
cpu-show-menu=true
memory-show-menu=true
disk-show-menu=false
cpu-graph-width=100
cpu-display=true
battery-show-menu=false
cpu-refresh-time=500
swap-show-text=false
net-show-menu=true
thermal-show-menu=true
disk-show-text=false
cpu-show-text=true
memory-show-text=false
```
