### ISSUE TITLE
Arch linux + Gnome frame drop

### ISSUE THREAD

**Issue by PierfrancescoArdino** [paradoxxxzero/gnome-shell-system-monitor-applet#417]
It seems that using this extension creates frame dropping/skipping under my system. Without it everything is ok. ArchLinux + Gnome 3.26

**Comment by kdistin** [comment]
This is happening for me on Fedora 27 too.
Again with the extension turned off everything is fine.

**Comment by xorain** [comment]
I can also confirm this bug, running GNOME 3.26.2 / Wayland / Arch Linux.
The frame drops correspond to the chosen refresh time for **CPU frequency** monitoring. The problem disappears if I disable CPU frequency monitoring. 

In my experience, this bug only occurs in combination with linux 4.13 or newer.
There are no frame drops using the 4.9-lts kernel, or downgrading to the 4.12 series.

**Comment by ondrejtichacek** [comment]
The bug is still present running GNOME 3.30.2 / Wayland / Arch Linux (kernel 4.20)

I spent a lot of time figuring out that this behavior is actually caused by the system-monitor-applet. I suggest displaying a warning in the applet Frequency tab.

**Comment by return42** [comment]
@ondrejtichacek : I made a fork [1] with the patch in @14mRh4X0r suggested. For me it fixed a lot of my issues I observed when system-monitor is activated. May you also like to have a look at #496 which summarize all the issues related to blocking IO.

Do you like to test my fork? .. any feedback is welcome / Thanks

[1] https://github.com/return42/gnome-shell-system-monitor-applet

**Comment by return42** [comment]
@ondrejtichacek @kdistin @xorain This issue is fixed in master since PR #497 is merged. 
@PierfrancescoArdino can you please test current master and close this issue? / Thanks!
