### ISSUE TITLE
Arch Linux: Extension crashes after lock screen

### ISSUE THREAD

**Issue by dkumor** [paradoxxxzero/gnome-shell-system-monitor-applet#419]
The extension loads fine after login, but after leaving computer idle until it goes to lockscreen, and unlocking, the extension is gone.

The following show up in journalctl log for gnome-shell
```
System monitor applet disable
System monitor applet enabling
Extension "system-monitor@paradoxxx.zero.gmail.com" had error: Error: Object Gio.Settings (0x564de4bfe520), has been already deallocated - impossible to access to it. This might be caused by the fact that the object has been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs
```

I am using the AUR version of the extension: https://aur.archlinux.org/packages/gnome-shell-extension-system-monitor-git/
This issue showed up recently, and upgrading to most recent AUR version did not help. 

I am using a fully updated system (Gnome 3.26.2), the issue has persisted through multiple reboots.

Any suggestions?

**Comment by FSMaxB** [comment]
@dkumor: Try downgrading gjs to 1.50.2, this might be related to https://gitlab.gnome.org/GNOME/gjs/issues/21

Essentially the GNOME folks changed gjs in such a way, that it crashes when destroyed objects are used from JavaScript from my understanding.

**Comment by franglais125** [comment]
@FSMaxB Thanks a lot for the tip. I've seen very similar errors suddenly being reported on various extensions. It seems that a few fixes will need to be applied here and there,

**Comment by dkumor** [comment]
@FSMaxB I can confirm, downgrading gjs to `gjs-1.50.2-1` seems to have fixed the problem based on an initial test.

For clarity, this was the command used:
```
sudo pacman -U /var/cache/pacman/pkg/gjs-1.50.2-1-x86_64.pkg.tar.xz
```

Since this is a workaround, should I leave this issue open?

**Comment by franglais125** [comment]
@dkumor I'd leave it open, as eventually this will affect more users. I'll try to tackle this once the newer package is available on Debian. If someone else can debug this, then we can perhaps find the source of the problem sooner.

Following the link to the gitlab issue, it seems that the crash will be "downgraded" to a warning relatively soon, so perhaps when that happens it will be easier to spot the error (and nicer for users anyway!).

**Comment by auipga** [comment]
the workaround by @dkumor doesn't work for me. I tried `gjs-1.50.2-1` and `gjs-1.50.1-1`

**Comment by noreun** [comment]
Same problem here at Manjaro (was using gjs 1.50.4-1). I downgraded to 1.50.2-1 and I now I can inspect my journal again :) 
It was showing ~15 lines every couple seconds. The stack trace shows the offending lines, might help to debug the issue:

```
Jan 30 17:26:29 gnome-shell[18472]: Object Gio.Settings (0x5654a0821880), has been already deallocated - impossible to access to it. This might be caused by the fact that the object has been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs
Jan 30 17:26:29 org.gnome.Shell.desktop[18472]: == Stack trace for context 0x56549e769170 ==
Jan 30 17:26:29 org.gnome.Shell.desktop[18472]: #0 0x7ffe40c0f310 b   /home/leobar/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/extension.js:1744 (0x7fa56762fde0 @ 39)
Jan 30 17:26:29 org.gnome.Shell.desktop[18472]: #1 0x7ffe40c0f370 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fa5d84c2bc0 @ 71)
Jan 30 17:26:29 org.gnome.Shell.desktop[18472]: #2 0x7ffe40c0f370 I   /home/leobar/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/extension.js:897 (0x7fa56762d2b8 @ 59)
Jan 30 17:26:29 org.gnome.Shell.desktop[18472]: #3 0x7ffe40c0f3d0 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fa5d84c2bc0 @ 71)
Jan 30 17:26:29 org.gnome.Shell.desktop[18472]: #4 0x7ffe40c0f460 I   self-hosted:913 (0x7fa5d84ee5e8 @ 346)
Jan 30 17:26:29 org.gnome.Shell.desktop[18472]: == Stack trace for context 0x56549e769170 ==
Jan 30 17:26:29 org.gnome.Shell.desktop[18472]: #0 0x7ffe40c0f310 b   /home/leobar/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/extension.js:1756 (0x7fa56762fde0 @ 235)
Jan 30 17:26:29 org.gnome.Shell.desktop[18472]: #1 0x7ffe40c0f370 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fa5d84c2bc0 @ 71)
Jan 30 17:26:29 org.gnome.Shell.desktop[18472]: #2 0x7ffe40c0f370 I   /home/leobar/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/extension.js:897 (0x7fa56762d2b8 @ 59)
Jan 30 17:26:29 org.gnome.Shell.desktop[18472]: #3 0x7ffe40c0f3d0 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fa5d84c2bc0 @ 71)
Jan 30 17:26:29 org.gnome.Shell.desktop[18472]: #4 0x7ffe40c0f460 I   self-hosted:913 (0x7fa5d84ee5e8 @ 346)
Jan 30 17:26:29 gnome-shell[18472]: Object Gio.Settings (0x5654a0821880), has been already deallocated - impossible to access to it. This might be caused by the fact that the object has been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs
Jan 30 17:26:29 org.gnome.Shell.desktop[18472]: == Stack trace for context 0x56549e769170 ==
Jan 30 17:26:29 org.gnome.Shell.desktop[18472]: #0 0x7ffe40c0f310 b   /home/leobar/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/extension.js:1805 (0x7fa5676322b8 @ 39)
Jan 30 17:26:29 org.gnome.Shell.desktop[18472]: #1 0x7ffe40c0f370 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fa5d84c2bc0 @ 71)
Jan 30 17:26:29 org.gnome.Shell.desktop[18472]: #2 0x7ffe40c0f370 I   /home/leobar/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/extension.js:897 (0x7fa56762d2b8 @ 59)
Jan 30 17:26:29 org.gnome.Shell.desktop[18472]: #3 0x7ffe40c0f3d0 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fa5d84c2bc0 @ 71)
Jan 30 17:26:29 org.gnome.Shell.desktop[18472]: #4 0x7ffe40c0f460 I   self-hosted:913 (0x7fa5d84ee5e8 @ 346)
```

**Comment by franglais125** [comment]
Would you mind testing https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/pull/426 ?

It fixes the error messages for me.

**Comment by noreun** [comment]
@franglais125 it seems to do the trick! I upgraded gjs and the messages are gone.

**Comment by timn** [comment]
Works for me, too. This is on Fedora 27 (Gnome 3.26.2, gjs 1.50.4). Thanks @franglais125 .

**Comment by franglais125** [comment]
I merged the fix into master. I'll close this issue now, please reopen/report again if the problem persists.
