### ISSUE TITLE
Adjustable display size

### ISSUE THREAD

**Issue by darkdragon-001** [paradoxxxzero/gnome-shell-system-monitor-applet#420]
The graph is too big on my laptop (it does not fit between time and battery information) on Ubuntu 17.10.
I tried setting _Compact Mode_ and adjusting _Graph Width_ without any notable change.
I would like to adjust the display width (in pixels?) of each graph.

**Comment by franglais125** [comment]
*Compact Mode* as well as *Graph Width* often require that you reload the extension completely. You can try disabling and re-enabling it, or simply logging out and back in (`Alt + F2 + r` works on X of course).
