### ISSUE TITLE
Extension won't work if locale LANGUAGE has no value set

### ISSUE THREAD

**Issue by d97jro** [paradoxxxzero/gnome-shell-system-monitor-applet#421]
If the locale LANGUAGE is unset, the extension won't start and this error message will be found in the logs:

gnome-shell[28515]: Extension "system-monitor@paradoxxx.zero.gmail.com" had error: RangeError: invalid language tag: C

With LANGUAGE set e.g. to

LANGUAGE=en_US:en

the extension works.
From a user perspective, I guess the expected behavior would be fallback to US English when not set (or maybe I'm just being old school ;-) )

No issue for me any longer, since I have now properly set LANGUAGE, but I thought I'd let you know.

Cheers,

/J

**Comment by chrisspen** [comment]
Good to know. However, there's not much we can do about this unless someone wants to add language support for the "C" locale.
