### ISSUE TITLE
[Info] Needs Gnome 3.26 support in extension.gnome.org

### ISSUE THREAD

**Issue by ceyhunn** [paradoxxxzero/gnome-shell-system-monitor-applet#422]
Hi @maweki, please review the gnome-shell-extension-system-monitor  new versions.

**Comment by westial** [comment]
Gnome 3.26.2-4 error loading extension:
`Extension "system-monitor@paradoxxx.zero.gmail.com" had error: TypeError: NMClient.Client is undefined`

**Comment by dhd0004** [comment]
I have the same problem

**Comment by pubcoder** [comment]
@westial this has been fixed on github but is not distributed on extensions.gnome.org yet.

**Comment by westial** [comment]
Right, master branch works. Thank you @pubcoder. I really love this extension.

**Comment by hemebond** [comment]
I just get some sort of timeout:
```
$ gnome-shell-extension-tool --reload-extension=system-monitor@paradoxxx.zero.gmail.com
Traceback (most recent call last):
  File "/usr/bin/gnome-shell-extension-tool", line 232, in <module>
    main()
  File "/usr/bin/gnome-shell-extension-tool", line 225, in main
    reload_extension(options.reload)
  File "/usr/bin/gnome-shell-extension-tool", line 194, in reload_extension
    None)
GLib.Error: g-io-error-quark: Timeout was reached (24)
```

**Comment by Darcidride** [comment]
Thank you for the information @pubcoder 
I will take the head of master version but... for everyone else that dont know, can you at least put a message on the extension description on the Gnome shell extension website ? (until you update the version on the website)
Thank you in advance,

**Comment by tvld** [comment]
The extension really looks superb... sadly it kills my other notifications. So, sadly, can't really use it reliably for now (Ubuntu 17.10; GNOME Shell 3.26.2)

**Comment by gnumoksha** [comment]
An example for install the new version that works on Gnome 3.26:
```
git clone --depth=1 https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet.git ~/.local/share/gnome-shell/extensions/system-monitor-complete
mv ~/.local/share/gnome-shell/extensions/system-monitor-complete/system-monitor@paradoxxx.zero.gmail.com ~/.local/share/gnome-shell/extensions/
rm -Rf ~/.local/share/gnome-shell/extensions/system-monitor-complete
gnome-shell-extension-tool --enable-extension=system-monitor@paradoxxx.zero.gmail.com
```
Then press `Alt+F2`, type `r` and `enter`.

**Comment by vstepaniuk** [comment]
> git clone --depth=1 https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet.git ~/.local/share/gnome-shell/extensions/system-monitor-complete
> mv ~/.local/share/gnome-shell/extensions/system-monitor-complete/system-monitor@paradoxxx.zero.gmail.com ~/.local/share/gnome-shell/extensions/
> rm -Rf ~/.local/share/gnome-shell/extensions/system-monitor-complete
> gnome-shell-extension-tool --enable-extension=system-monitor@paradoxxx.zero.gmail.com

Ubuntu 17.10 x64, GNOME 3.26.2

missing dependencies:

libgtop
Network Manager
gir1.2-gtop-2.0
gir1.2-networkmanager-1.0

**Comment by ceyhunnabiyev** [comment]
System-monitor v34 has High CPU usage. But with version 32 it is Ok on Manjaro.
