### ISSUE TITLE
Disk unit style

### ISSUE THREAD

**Issue by franglais125** [paradoxxxzero/gnome-shell-system-monitor-applet#442]
As reported by @waldyrious , there is no space between the unit "MiB/s" and the type "R/W". The result is a line that reads as:

![screenshot from 2018-03-21 01-17-38](https://user-images.githubusercontent.com/19195975/37695453-b559efae-2ca5-11e8-9b68-203e332fe8ba.png)

**Comment by waldyrious** [comment]
Cross-linking #338 for future reference.

**Comment by franglais125** [comment]
Fixed in [433894e59235932ab532d05a521582423653e579]. Thanks!
