### ISSUE TITLE
Extension info/error logs dominating syslog journal

### ISSUE THREAD

**Issue by cbcoutinho** [paradoxxxzero/gnome-shell-system-monitor-applet#447]
I've been noticing for the last few days that this extension has been completely dominating my syslog files on OpenSUSE Tumbleweed. I can see that every second I'm getting the following error/info notification:

```
apr 02 11:34:20 tumbleweed gnome-shell[4779]: Object Gio.Settings (0x560ec4fc4a10), has been already deallocated - impossible to access to it. This might be caused by the fact that the object has been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs
apr 02 11:34:20 tumbleweed gnome-shell[4779]: Object Gio.Settings (0x560ec4fc4a10), has been already deallocated - impossible to access to it. This might be caused by the fact that the object has been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs
apr 02 11:34:20 tumbleweed org.gnome.Shell.desktop[4779]: == Stack trace for context 0x560ebcf1a040 ==
apr 02 11:34:20 tumbleweed org.gnome.Shell.desktop[4779]: #0 0x7ffd36078c30 I   /home/chris/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/extension.js:1936 (0x7fa96b6c5098 @ 39)
```

I'm not sure what these errors mean, but the fact that this is practically 99% of my system log files when the extension is activated makes my logs practically useless. I would appreciate some guidance here. Are these true errors or is the logging here just overly verbose? Is there a way to redirect it to another file or turn it off completely?

**Comment by franglais125** [comment]
Normally, this was fixed in [2efb9d1248e719474eab91d92d0905f5d3e1d25c]. Would you mind trying with the latest master?

**Comment by guilhem** [comment]
@franglais125 indeed it fixed the problem
Is it possible to release a new version with this patch ? :)

**Comment by cbcoutinho** [comment]
Yea I think this solved the problem. Thanks for the tip!
