### ISSUE TITLE
Gnome-Ubuntu Fahrenheit for Thermal Monitor not correctly changing unit string

### ISSUE THREAD

**Issue by rawells14** [paradoxxxzero/gnome-shell-system-monitor-applet#448]
The thermal temperature does not correctly display the units on the status bar. When changing to Fahrenheit, the "C" is displayed instead of an "F". The actual number and modal that comes down when clicked is correct however.

**Comment by franglais125** [comment]
Some features require that you restart the shell. For this one, would you mind trying to restart it?

**Comment by the-confessor** [comment]
I have experienced this too, even after a restart.

**Comment by the-confessor** [comment]
This appears to be a duplicate of 344.

**Comment by rawells14** [comment]
Seems to be fixed now
