### ISSUE TITLE
Please stop rebasing on master

### ISSUE THREAD

**Issue by piegamesde** [paradoxxxzero/gnome-shell-system-monitor-applet#455]
As far as I can see it, the latest commits on master (those since the v34 tag) are rebases instead of merges. This means that all branches effectively are out of date and have to merge master into them or have to rebase onto master. Both options are tedious, time consuming and error-prone and, most importantly, totally unnecessary if you would merge PR onto master instead of rebasing it.

If you didn't rebase anything, how did this happen? Whatever it actually is, please make it stop.

**Comment by franglais125** [comment]
This is not what is done in general, it was more of a one-time thing.

We wanted to include 3.28 support a soon as possible, and the quickest way to do it was to perform a rebase (i.e., reorder some commits, effectively rewriting history on master). The reason was that there was a very long queue of extension reviews on e.g.o.

**Comment by piegamesde** [comment]
Is there a way to submit other branches than the master to e.g.o? Making a separate release branch would have helped avoiding this issue.

**Comment by franglais125** [comment]
Sure, but then we are left with a weird tag history on our master branch, that we essentially can't get rid of. For instance, in that case, v34 would have been nowhere to be found on the master branch.

From this point of view, rebasing a few commits was, IMO, a simpler approach. But don't worry, this is not something we are doing all the time. As I said, we wanted to provide 3.28 support quickly, and were stuck with a long queue on e.g.o.

**Comment by chrisspen** [comment]
What about something like http://nvie.com/posts/a-successful-git-branching-model/ ?

**Comment by piegamesde** [comment]
Personally, I think branching models are heavily dependent on the actual project and working environment. That specific proposal might be a little overkill for this extension, but any branching model is better than none, so I'm not against it.
