### ISSUE TITLE
Ubuntu 18.04 - Preferences not opening

### ISSUE THREAD

**Issue by tryfon** [paradoxxxzero/gnome-shell-system-monitor-applet#456]
Error: Requiring Clutter, version none: Typelib file for namespace 'Clutter' (any version) not found

Stack trace:
  @/home/tryfon/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/prefs.js:5:7
  _getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:75:13
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:90:31
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:243:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:397:5
  @<main>:1:43

All clutter dependencies seem to be installed:
apt list --installed | grep -i clutter

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

clutter-1.0-tests/bionic,now 1.26.2+dfsg-4 amd64 [installed]
gstreamer1.0-clutter-3.0/bionic,now 3.0.26-1 amd64 [installed]
libclutter-1.0-0/bionic,now 1.26.2+dfsg-4 amd64 [installed]
libclutter-1.0-common/bionic,bionic,now 1.26.2+dfsg-4 all [installed]
libclutter-gst-3.0-0/bionic,now 3.0.26-1 amd64 [installed]
libclutter-gtk-1.0-0/bionic,now 1.8.4-3 amd64 [installed]

**Comment by franglais125** [comment]
Perhaps you are missing some bindings? I also have these installed:

```
gir1.2-clutter-1.0
gir1.2-clutter-gst-3.0
gir1.2-gtkclutter-1.0
```

**Comment by andrewlively** [comment]
@franglais125 I'm on 18.04 and had this same issue. You're suggestion fixed it. Just ran:

```shell
$ sudo apt install gir1.2-clutter-1.0 gir1.2-clutter-gst-3.0 gir1.2-gtkclutter-1.0
```

**Comment by rowkc** [comment]
tank...

**Comment by Bilge** [comment]
Only `sudo apt install gir1.2-clutter-1.0` is needed. You do not need `gir1.2-clutter-gst-3.0` or `gir1.2-gtkclutter-1.0`.

**Comment by auipga** [comment]
For **Archlinux** users: install clutter-gtk
