### ISSUE TITLE
Ubuntu 18.04 Hang Moving Windows

### ISSUE THREAD

**Issue by Queuecumber** [paradoxxxzero/gnome-shell-system-monitor-applet#462]
I noticed that when this extension is enabled things hang periodically, the effect is most noticeable when moving windows around on the desktop. The hang seems to happen once every second regardless of what I change the refresh rates of the various metrics to. I know it is this extension because I tried all of them until I found that when I disable this one, the problem goes away, and when I reenable it, the problem immediately comes back.

**Comment by Queuecumber** [comment]
I actually just narrowed this down a little, it is only if I have the CPU frequency display turned on. That display actually doesnt seem to work if I toggle it mid-session, I need to log out and log in to fix it. Hanging only happens when it is turned on and functional

**Comment by piegamesde** [comment]
Please check if this is yet another duplicate of #433

**Comment by Queuecumber** [comment]
It is indeed, sorry I missed that issue, I'll try the branch and let you know
