### ISSUE TITLE
Extension is *too* good? (thank you thread)

### ISSUE THREAD

**Issue by NickSto** [paradoxxxzero/gnome-shell-system-monitor-applet#466]
Maybe this isn't the right place, but I just got this installed and it works like a dream, and I wanted to thank you for developing this fantastic extension.

I've used indicator-multiload for years, and I can't imagine living without that 6th sense of what my computer is up to at all times. I'm currently on Ubuntu 16.04, so when I heard about the move to Gnome I was nervous. I desperately hoped that my little graphs would somehow keep working (or that I could find an alternative even half as good).

But I just installed 18.04 in a VM, found your extension, and got it working. And it's even better than indicator-multiload! It's even more customizable, and it's got even more sensors. I can finally rest easy!

Thank you!

**Comment by de-vries** [comment]
Thanks for the system monitor. I somehow find the little graphs in the top panel oddly comforting.

Kind regards,

Another former multiload user

**Comment by ryneches** [comment]
Without this extension, there is no way I would have stuck with gnome-shell. The only thing that would make it better is if it were officially part of Gnome.

Actually... is there any way we could get that to happen?

**Comment by de-vries** [comment]
\o/ Thanks for the update!
