### ISSUE TITLE
System Monitor does not open

### ISSUE THREAD

**Issue by beruic** [paradoxxxzero/gnome-shell-system-monitor-applet#474]
Whenever I click the menu entry for _System Monitor_, nothing happens. I cannot see any errors in Looking Glass.

OS: Ubuntu 18.04.1

**Comment by beruic** [comment]
After digging a bit, I think this issue roots in the fact that the Gnome System Monitor on Ubuntu 18.04 seems to be installed as a snap.

**Comment by beruic** [comment]
Ok, this is definitely the issue.

I ran `Shell.AppSystem.get_default().lookup_app('gnome-system-monitor.desktop')` in Looking Glass, which returned a big fat `null` (which should probably be detected by _gnome-shell-system-monitor-applet_).
Then I installed the system monitor from the repository with `$ sudo apt install gnome-system-monitor`, and `Shell.AppSystem.get_default().lookup_app('gnome-system-monitor.desktop')` now returns `[object instance proxy GIName:Shell.App jsobj@0x7f6fe90923d0 native@0x55ee9acbeb40]` and I can open the Gnome System Monitor from the menu of _gnome-shell-system-monitor-applet_.

I guess the solution here is either to advice the user to install the apt-version, or somehow detect the .desktop file from the snap.

**Comment by A33a** [comment]
Confirm the issue. And thanks for the workaround, @beruic. It did work. :)

**Comment by scroom** [comment]
Same problem here on Ubuntu 18.10.

**Comment by bittner** [comment]
How do we solve this issue for everyone? Why is gnome-system-monitor installed as a snap at first? I can't remember I did this, and I don't see which dependency brought it in. Is this installed with the Ubuntu installer by default?

**Comment by airvb** [comment]
I confirm the snag on ubuntu 18-04
i check that gnome-system-monitor is running with 
`snap list`
After that, remove the snap by : 
`sudo snap remove gnome-system-monitor`
and install the apt version by :
`sudo apt install gnome-system-monitor`

Reboot, 

ops ok !
tks @beruic

**Comment by darkxst** [comment]
There are about a half dozen core GNOME apps that are now installed as snaps rather than deb packages (atleast on new installs, not sure about upgrades), this work landed a while back, 17.10 or 18.04 at a guess. And yes gnome-system-monitor is one of them!

**Comment by bittner** [comment]
I have made a [bug report on Launchpad](https://bugs.launchpad.net/ubuntu/+source/gnome-system-monitor/+bug/1819263) about the issue to bring it to the attention of Canonical.

Everyone affected by this problem is welcome to mark this bug with "This bug affects me" (by clicking on the link at the top of the bug report).

**Comment by return42** [comment]
The bug on launchpad is closed .. lets close this issue too.

**Comment by beruic** [comment]
So does this mean that I can use the snap version of `gnome-system-monitor` again?
