### ISSUE TITLE
Breaks Gnome 3.30

### ISSUE THREAD

**Issue by tiotrom** [paradoxxxzero/gnome-shell-system-monitor-applet#488]
Having this extension installed is going to break a few things. The most serious of them all is the "admin password" dialogue. With it enabled, after a while of use (a few hours) if say you want to install a new application and that will require the gnome admin password popup, then the popup will never show up unless you restart the shell. It took me months to figure out that it was this extension. I had to test all extensions one by one. And overall this extensions makes the shell unstable (it randomly restarts).
 
I love it though, but I cannot use it. 

Note: installed via the gnome website and/or Manjaro repositories. Both are creating the above issues.

Cheers and thanks for your work!

**Comment by return42** [comment]
This bug should be fixed / did you tried a new installation?

**Comment by tiotrom** [comment]
I think the latest works yes! You can close this one. Thanks!

**Comment by return42** [comment]
I'am not the maintainer, I can't close it .. its up to you :)
