### ISSUE TITLE
New release please

### ISSUE THREAD

**Issue by brianjmurrell** [paradoxxxzero/gnome-shell-system-monitor-applet#492]
#458 is a crasher and #461 fixes it.  That fix is over 4 months old.  The latest release is even older than that.

When will a new release be made that includes at least a bug fix for a crasher that a number of people have been experiencing?  Surely creating a new release is not so difficult that it cannot just be done.  Surely master has not completely destablized since the last release.

And even if it has, this crasher being so old and affecting so many people at least deserves a point release IMHO.

So, can we get a new release in the very near future please?

**Comment by p91paul** [comment]
I think that before seeing a new release there is the need of someone willing to step up and maintain this extension. That means contacting the owner of this repository, asking for membership, then contact reviewers at extensions.gnome.org and get ownership of the extension there (I'm sure current owner will be glad to hand it over).

**Comment by ryneches** [comment]
Are you volunteering? :-)

**Comment by p91paul** [comment]
I already maintain a handful of gnome-shell extensions and struggle with those...I'm good thanks :) 
I just think that asking others to do work for you for free requires at least a bit of kindness. I think the developers and maintainers deserve that more than any of us deserve anything from them... That's why I described how this should work, maybe OP wanted to volunteer instead of just ranting.

**Comment by brianjmurrell** [comment]
OP is not really a JS developer (or a GNOME[-shell] developer) in any sense of being able to reasonably and responsibly take ownership of a JS gnome-shell module, nor does he have time to learn yet another language and moreover another (i.e. gnome-shell) interface.  Maybe one day when he retires.

I guess I didn't think it was such a big deal to either just release master as it is or land one fix to the current release and release a point-fix.

The point still remains that a new release was even done, after the aforementioned fix was landed but just failed to include it and as such, yet another release exists in extensions.gnome.org that continues to crash, which I am ignoring because upgrading to it will wipe out my local copy with the crashing fix applied.

I guess I will just stop _ranting_ and continue to use my local copy with the crasher fixed.

**Comment by chrisspen** [comment]
I've merged #461 and a couple other PRs. If someone could do a final review of master, I'll do a release sometime in the next week.

**Comment by brianjmurrell** [comment]
I have it running here.  It seems to load OK and run.  I would assume the leak is fixed but it usually take a day or two for that to show up.

Just pushed #495 for anyone wanting to iterate on reloading the extension easily.

**Comment by 4javier** [comment]
Please coud you start packaging releases here in github? gnome extension official site has a terrible review policy, and having a tar available here would make easier for Arch user (and not only) to have a pkgbuild downloading a stable version, instead of pulling a git repo.

**Comment by chrisspen** [comment]
@4javier By releases on github, you mean [this page](https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/releases)? I've been infrequently making those, since I didn't think anyone used it, but it's that's preferable to a slower gnome extension release, I'll add it to my release procedure.

**Comment by 4javier** [comment]
Exactly, thanks. 
At the moment the only PKGBUILD existing on AUR for your extension, is git pull based. I could maintain a stable one using those tars as source.

**Comment by chrisspen** [comment]
I'm waiting on some final feedback on master, as well as some open PRs. I'm also testing master. Assuming nothing comes up, I'll create a release next weekend.

**Comment by hackel** [comment]
While it's not critical to package up an official "Github release," tagging the specific versions uploaded to EGO is absolutely essential.

**Comment by agonzale34** [comment]
I'm testing with master on Manjaro with gnome 3.32 and it's working pretty well.

**Comment by 4javier** [comment]
> While it's not critical to package up an official "Github release," tagging the specific versions uploaded to EGO is absolutely essential.

Problem with EGO is their extremely slow review policy. A lot of extensions are already updated to .32, but the new versions are not accepted because of lack of reviewers.

**Comment by return42** [comment]
I guess this issue is obsolete / if so, please close!
