### ISSUE TITLE
installation(dep issue) fails on Debian(testing)

### ISSUE THREAD

**Issue by alirezaimi** [paradoxxxzero/gnome-shell-system-monitor-applet#494]
Hi

	root@alidev:~# apt-get install gir1.2-nm-1.0 gir1.2-gtop-2.0 
	Reading package lists... Done
	Building dependency tree       
	Reading state information... Done
	gir1.2-gtop-2.0 is already the newest version (2.38.0-4).
	gir1.2-nm-1.0 is already the newest version (1.14.4-4).
	0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

there is no package in debian testing `gir1.2-networkmanager-1.0`

	root@alidev:~# apt-get install gir1.2-gtop-2.0 gir1.2-networkmanager-1.0  gir1.2-clutter-1.0
	Reading package lists... Done
	Building dependency tree       
	Reading state information... Done
	Package gir1.2-networkmanager-1.0 is not available, but is referred to by another package.
	This may mean that the package is missing, has been obsoleted, or
	is only available from another source
	However the following packages replace it:
	  gir1.2-nm-1.0

	E: Package 'gir1.2-networkmanager-1.0' has no installation candidate

**Comment by p91paul** [comment]
the error message implies gir1.2-nm-1.0 replaces gir1.2-networkmanager-1.0, so you should be good without it!

**Comment by alirezaimi** [comment]
@p91paul No, error still exist :
![photo_2019-01-16_12-13-10](https://user-images.githubusercontent.com/1029949/51236723-1fb96080-1988-11e9-85ef-7131a2de8df0.jpg)

**Comment by Myoldmopar** [comment]
I am also seeing this same thing when installing from a browser in Ubuntu 18.10:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.10
Release:	18.10
Codename:	cosmic

$ gnome-shell --version
GNOME Shell 3.30.1

$ dpkg -s gir1.2-gtop-2.0 | grep Version
Version: 2.38.0-2ubuntu0.18.04.1

$ dpkg -s gir1.2-networkmanager-1.0 | grep Version
Version: 1.12.4-1ubuntu1.2

$ dpkg -s gir1.2-nm-1.0 | grep Version
Version: 1.12.4-1ubuntu1.2
```

**Comment by JuliusSenkus** [comment]
Also seing same issue.

**Comment by UMLAUTaxl** [comment]
Same. 
But Niffo had success: https://extensions.gnome.org/extension/120/system-monitor/

**Comment by return42** [comment]
Lets close this issue, duplicate: #389

**Comment by UMLAUTaxl** [comment]
Also since this solved itself for me.
