### ISSUE TITLE
v36 does not support GS 3.31.90 (3.32)

### ISSUE THREAD

**Issue by dino99** [paradoxxxzero/gnome-shell-system-monitor-applet#505]

**Comment by dino99** [comment]
ubuntu 19.04
Have upgraded GS from 3.30.2 to 3.31.90, and that breaks system-monitor: all icons gone.
So waiting an upgrade supporting the new coming Gnome-Shell 3.32

**Comment by xinke2411** [comment]
I have same problem on ubuntu 19.04 with gnome-shell 3.31.90 .

**Comment by Hentioe** [comment]
Gnome-Shell 3.32 has been released and is no longer compatible.
