### ISSUE TITLE
Support for GNOME Shell 3.32.0

### ISSUE THREAD

**Issue by srinskit** [paradoxxxzero/gnome-shell-system-monitor-applet#511]
Extension doesn't work with GNOME Shell 3.32.0.

System details:

> $ gnome-shell --version
> GNOME Shell 3.32.0
> $ uname -r
> 5.0.2-arch1-1-ARCH
>

**Comment by Hentioe** [comment]
+1

**Comment by MasinAD** [comment]
+1
According to lg:
> TypeError: this._construct is undefined

**Comment by allexlima** [comment]
+1

**Comment by TheBlackKoala** [comment]
+1

**Comment by alephnull** [comment]
See #508

**Comment by BloodyIron** [comment]
Once this is addressed can we get a new release with notes please? Haven't had one on github since Aug 2018...

**Comment by soaringowl2145** [comment]
When this does get fixed will the version in the Ubuntu 19.04 repository be updated with the fix?

**Comment by chrisspen** [comment]
I've merged #510 so master should now support Gnome 3.32. I'm going to poll some other PR authors to update conflicts and try to get their fixes in before I push another release. In the meantime, please test master and confirm this resolves issues on Ubuntu 19.

**Comment by soaringowl2145** [comment]
> I've merged #510 so master should now support Gnome 3.32. I'm going to poll some other PR authors to update conflicts and try to get their fixes in before I push another release. In the meantime, please test master and confirm this resolves issues on Ubuntu 19.

What is a PR author?

**Comment by chrisspen** [comment]
@soaringowl2145 The author of a pull request :)

**Comment by zeppe** [comment]
> In the meantime, please test master and confirm this resolves issues on Ubuntu 19.

It works on Ubuntu 19.02.

**Comment by BloodyIron** [comment]
@zeppe do you mean Ubuntu 19.04?

**Comment by dr-br** [comment]
Does work on Ubuntu 19.04 with Wayland. X11 suffers from "LOOOOOOONNNNG login times with system-monitor enabled" as described in #515 (login not possible at all)

**Comment by zeppe** [comment]
> 
> 
> @zeppe do you mean Ubuntu 19.04?

:) yes of course, sorry.

**Comment by jendakol** [comment]
FYI master works for me on Ubuntu 19.04:
```
GNOME Shell 3.32.0
5.0.0-13-generic
```
Didn't observe any slowdown (tried only lock & login though).

**Comment by BloodyIron** [comment]
Still only see 3.30 support on : https://extensions.gnome.org/extension/120/system-monitor/

Also, releases section of this github project shows no releases since Aug 2018... CMON GUYS.

**Comment by skyghis** [comment]
@chrisspen  `master` works on my Ubuntu 19.04 without any issue.

- **No** long login issue
- Preference dialog display fine
- Popup windows show up to date information and refresh in real time.

Thanks @shemgp for the  good work :+1: 

Should probably bake release.

**Comment by chrisspen** [comment]
I've [published a new release](https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/releases/tag/v38), and have uploaded it to EGO for review.

**Comment by chrisspen** [comment]
The release has been approved and is now public on the extensions site.

**Comment by ryneches** [comment]
When I re-enabled it on Ubuntu 19.04 with Wayland, I ran into a weird case where it kept loading new instances of system-monitor until it filled the entire menubar. Restarting the desktop environment cleared the problem, and now it's running fine.

I've run into weird behavior before when loading a Gnome applet for the first time, so I'm not sure if this is a bug in system-monitor. Some initialization code to make sure the applet isn't already running might help avoid edge cases.
