### ISSUE TITLE
Fails to load in Ubuntu 19.04

### ISSUE THREAD

**Issue by moorepants** [paradoxxxzero/gnome-shell-system-monitor-applet#521]
The gnome-shell-system-monitor package in Ubuntu 19.04 seems to no longer load. This is what I see from gnome tweaks:
![2019-05-10_15-02](https://user-images.githubusercontent.com/276007/57558977-b6919a80-7334-11e9-9ff7-e84528d93a76.png)
The alert icon displays "Error loading extension" when the mouse hovers over it.
I've tried reinstalling the package but it still fails to load.

**Comment by Derek-Wds** [comment]
Same problem on Ubuntu 18.04.2 LTS, with GNOME shell version 3.28.3. I have tried any solutions that I could find, but none of them worked.

**Comment by chrisspen** [comment]
Most people seem to be running it on 18.04 with no problems, including myself. I'm running 3.28.3. What does your syslog say?

**Comment by Derek-Wds** [comment]
![Selection_035](https://user-images.githubusercontent.com/26081991/57648403-6b28f780-7593-11e9-9dd4-ba78249b40e6.png)
![Selection_036](https://user-images.githubusercontent.com/26081991/57648420-70864200-7593-11e9-94dc-3f88a896e122.png)

These are what I found in the syslog. I hope they helps.

Thanks,
Derek

**Comment by LaurentDumont** [comment]
Similar issue here : 

I have installed the pre-requisites packages.

```
 ~  sudo apt-get install gir1.2-gtop-2.0 gir1.2-networkmanager-1.0  gir1.2-clutter-1.0                                                                                                                        Mon 13 May 2019 11:05:38 PM EDT
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gir1.2-clutter-1.0 is already the newest version (1.26.2+dfsg-10).
gir1.2-gtop-2.0 is already the newest version (2.40.0-1).
gir1.2-networkmanager-1.0 is already the newest version (1.16.0-0ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

```

```

> ~  lsb_release -a                                                                                                                                                                                            Mon 13 May 2019 11:04:25 PM EDT
> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 19.04
> Release:	19.04
> Codename:	disco

```

```
May 13 23:00:48 smallpotato gnome-shell-ext[8925]: Some code called array.toString() on a Uint8Array instance. Previously this would have interpreted the bytes of the array as a string, but that is nonstandard. In the future this will return the bytes as comma-separated digits. For the time being, the old behavior has been preserved, but please fix your code anyway to explicitly call ByteArray.toString(array).#012(Note that array.toString() may have been called implicitly.)#0120 check_sensors() ["/home/ldumont/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/prefs.js":59]#0121 add() ["/home/ldumont/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/prefs.js":218]#0122 SystemMonitor_App/<() ["/home/ldumont/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/prefs.js":351]#0123 forEach() ["self-hosted":261]#0124 SystemMonitor_App() ["/home/ldumont/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/prefs.js":307]#0125 buildPrefsWidget() ["/home/ldumont/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/prefs.js":366]#0126 _selectExtension() ["resource:///org/gnome/shell/extensionPrefs/main.js":75]#0127 _onCommandLine() ["resource:///org/gnome/shell/extensionPrefs/main.js":320]#0128 _onCommandLine() ["self-hosted":979]#0129 main() ["resource:///org/gnome/shell/extensionPrefs/main.js":635]#01210 <TOP LEVEL> ["<main>":1]
May 13 23:00:48 smallpotato gnome-shell-ext[8925]: gtk_box_pack: assertion '_gtk_widget_get_parent (child) == NULL' failed
May 13 23:00:48 smallpotato gnome-shell-ext[8925]: message repeated 8 times: [ gtk_box_pack: assertion '_gtk_widget_get_parent (child) == NULL' failed]

```

**Comment by moorepants** [comment]
Maybe this is the same issue: https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/issues/508 and https://bugs.launchpad.net/ubuntu/+source/gnome-shell-extension-system-monitor/+bug/1819929

**Comment by santinoled** [comment]
Same issue. Was working on 18.04, after update to 19.04 stopped

**Comment by mominul** [comment]
I am also having this issue on Ubuntu 19.04

**Comment by EstherAF** [comment]
Same issue here in 19.04. 
To add some more info about the problem, when installing using firefox, it shows following message:

```
System Monitor Extensions
Dependencies Missing
Please install:
libgtop, Network Manager and gir bindings
     on Ubuntu: gir1.2-gtop-2.0, gir1.2-networkmanager-1.0
     ....
```

I've already install them successfully:
```
sudo apt-get install gir1.2-gtop-2.0 gir1.2-networkmanager-1.0  gir1.2-clutter-1.0
```

The error may be in the "libgtop"? I only can install libgtop2, and it's already installed. May it be that this plugin is not ready to integrate with libgtop**2**
```
dpkg -l | grep libgtop
ii  libgtop-2.0-11:amd64                       2.40.0-1                            amd64        gtop system monitoring library (shared)
ii  libgtop2-common                            2.40.0-1                            all          gtop system monitoring library (common)
```

**Comment by iTerminate** [comment]
After installing the dependencies it didn't work for me either. I restarted gnome and it worked. 

Here is everything I did to get it working: 
```
# maybe this isn't needed however it will install some additional optional gnome dependencies
sudo apt-get install gnome
# Install the dependencies for this application
sudo apt-get install gir1.2-gtop-2.0 gir1.2-networkmanager-1.0  gir1.2-clutter-1.0
# After this, it would still fail installing so I ran
gnome-shell --replace &
```

**Comment by return42** [comment]
On ubu-19.04 see [README](https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/blob/master/system-monitor%40paradoxxx.zero.gmail.com/README)

    sudo apt install gir1.2-gtop-2.0, gir1.2-networkmanager-1.0

Restart of desktop manager is needed, FYI:

    gnome-shell --replace &

only works in xorg (not with wayland).  If you are using wayland, logout & login and it works.

As far as I can see this issue is fixed / @moorepants can you please close it / thanks!

**Comment by moorepants** [comment]
I installed the two packages (networkmanager was not installed).  I then opened tweaks and it allowed me to turn on the the extension (couldn't before). Nothing changed. Then I ran the gnome-shell command. The monitor did not appear and tweaks didn't cause it to open. I restarted the computer and no applet appears. I opened tweaks and it is back to the previous state and will not allow me to turn on the applet. Seems to be the same as the original report.

**Comment by moorepants** [comment]
Some other notes. I am installing this extension using apt. The package doesn't have the networkmanager as dependency and is at version 36-1. If something has changed in the development version, this package may not be up-to-date.

```
moorepants@paravati:~$ aptitude show gnome-shell-extension-system-monitor 
Package: gnome-shell-extension-system-monitor
Version: 36-1
State: installed
Automatically installed: no
Priority: optional
Section: universe/gnome
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: all
Uncompressed Size: 276 k
Depends: gir1.2-clutter-1.0, gir1.2-gtop-2.0, gnome-shell
Description: Display system information in GNOME Shell status bar
 System information such as memory usage, cpu usage, network rates and more can be displayed in the notification area in GNOME Shell. 
 
 Settings can be accessed via gnome-tweak-tool where monitoring settings can be adjusted.
Homepage: https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet
```

**Comment by moorepants** [comment]
Yes, it seems that version 38 is available
![2019-09-27_07-43](https://user-images.githubusercontent.com/276007/65778332-96535400-e0fa-11e9-9b26-60c3a3ec655a.png)
 but not for 19.04:

**Comment by return42** [comment]
Correct, for ubu-19.04 you need v38, see [manual installation](https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet#manual-installation)

**Comment by moorepants** [comment]
Thanks, I'll just wait till 19.10.

**Comment by return42** [comment]
> Thanks, I'll just wait till 19.10.

You are welcome .. if it is fixed for you, don't forget to close the issue / thanks!

**Comment by moorepants** [comment]
I confirm that it now works in 19.10.
