### ISSUE TITLE
ByteArray.toString usage

### ISSUE THREAD

**Issue by rschupp** [paradoxxxzero/gnome-shell-system-monitor-applet#522]
@chrisspen  reverted the use of  ByteArray.toString in fc83a737e85f223bf7e5bdf0179f8e9b30dc1d13. IMHO that's not correct:

- I use the unreverted code and I **have** correct thermal display
- it may depend on the version of gjs (e.g. gnome-shell 3.32 requires >= 1.54.0)

Newer versions of gjs (I have 1.56.2) will emit lots of warnings if you **don't** use ByteArray.toString:
```javascript
$ gjs 
gjs> const Gio = imports.gi.Gio; 
gjs> const ByteArray = imports.byteArray 
gjs> let file = Gio.file_new_for_path("/sys/class/hwmon/hwmon0/temp1_input") 
gjs> let [ ok, contents ] = file.load_contents(null)
true,51000 

gjs> parseInt(contents) 
(gjs:2668): Gjs-WARNING **: 18:59:34.414: Some code called array.toString() on a Uint8Array instance. Previously this would have interpreted the bytes of the array as a string, but that is nonstandard. In the future this will return the bytes as comma-separated digits. For the time being, the old behavior has been preserved, but please fix your code anyway to explicitly call ByteArray.toString(array). (Note that array.toString() may have been called implicitly.) 
0 <TOP LEVEL> ["typein":16] 
1 <TOP LEVEL> ["<stdin>":1] 
51000 

gjs> parseInt(ByteArray.toString(contents)) 
51000 
```

**Comment by chrisspen** [comment]
The use of ByteArray.toString is not correct. I've confirmed it myself on Ubuntu 18.04. I'm sure it works in some more recent version of Gnome-Shell, but that's not what most people are using. Feel free to submit a patch that works for everyone.
