### ISSUE TITLE
Cpu freq and thermal showin NaN instead of values (please solve it !)

### ISSUE THREAD

**Issue by RafaelQuirino** [paradoxxxzero/gnome-shell-system-monitor-applet#526]
Since last update i'm getting NaNs instead of values. I know there is alread an issue, but i really rely on this extension, since my laptop have 12 cores and gets hot very  quickly. Please, solve it !

**Comment by chrisspen** [comment]
I've patched this in master. If you install from github, does that fix the problem?

**Comment by JMGama** [comment]
@chrisspen  have the same problem, installed from github and steal not working :disappointed:

**Comment by ryant18** [comment]
I didn't install from github, but I locally made the changes in c1af5103e86d4a0d03421c58f32efab689818b9c and it fixed the issue on ubuntu 18.04

**Comment by pabloab** [comment]
As said by @ryant18, just edit `~/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/extension.js` removing [those](https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/commit/c1af5103e86d4a0d03421c58f32efab689818b9c) `ByteArray.toString()` functions, restart with <kbd>Alt+F2,r </kbd> et voilà.

**Comment by zwn** [comment]
The same problem with cpu frequency and this fixed it for me:

```diff
        file.load_contents_async(null, function cb (source, result) {
            let as_r = source.load_contents_finish(result);
-            total_frequency += parseInt(ByteArray.toString(as_r[1]));
+            total_frequency += parseInt(as_r[1]);

            if (++i >= num_cpus) {
```

**Comment by bikubi** [comment]
Maybe this helps somebody: for me, the number wouldn't show up *at all* (not "NaN"), I had to change/touch Refresh Time to make it appear.

**Comment by recolic** [comment]
> Maybe this helps somebody: for me, the number wouldn't show up _at all_ (not "NaN"), I had to change/touch Refresh Time to make it appear.

I have exactly the same issue with you. I would like to add my steps to reproduce this issue: 

1. install this extension on gnome 41.2
2. In extension preference, set `Freq` to `Display`, and set `Display Style` to `digit`
3. Now it shows `        MHz` and it never update. I have been waiting for 10 minutes. 
4. Change `Refresh Time` from its default (1500) to 500. 
5. The problem got fixed.
