### ISSUE TITLE
GPU when active, crashed and stress PC, impossible to use.

### ISSUE THREAD

**Issue by marcosdissotti** [paradoxxxzero/gnome-shell-system-monitor-applet#531]
My ubuntu 18 crashed when i active GPU viewer, NaN values and stress CPU, RAM and others components, impossible utilize in gnome, i removed is it.

**Comment by kalilz4485** [comment]
FTR Someone posted this on https://extensions.gnome.org/extension/120/system-monitor/

> Dangerous for AMD GPU users! That's why 3 stars. Otherwise it works excellent. If you are using AMD and you enable GPU monitoring, your gnome will crash. To recover you'd have to have su enabled, log in as root, go to .local/share/gnome-shell/extensions/ system-monitor@..... delete file gpu....something.... with sh or js extension. It's a pain in the butt and if you don't know how to do it you're probably gonna reinstall your linux or something... Author. When you click on GPU tab or at settings windows show you should be checking for compatibility and disabling of AMD is present.
