### ISSUE TITLE
shell extension  overlaps my "gnome-tweak-tool"

### ISSUE THREAD

**Issue by Episodio1** [paradoxxxzero/gnome-shell-system-monitor-applet#535]
I insalled "gnome-tweak-tool" to show "date" in taskbar ( https://askubuntu.com/a/966634 ) and it seems my icons now overlap the "date":

![taskbar](https://user-images.githubusercontent.com/4375891/63428827-5e2c6780-c410-11e9-898f-8d88790a1167.jpg)

Is it a problem with "system-monitor" or anything else?

Thanks

**Comment by return42** [comment]
That is normal, there is no space left. Reduce size of you graphs and everything will be fine.
