### ISSUE TITLE
Doesn't work with GNOME Shell 3.36.0

### ISSUE THREAD

**Issue by nemoload** [paradoxxxzero/gnome-shell-system-monitor-applet#567]
Mar 13 16:26:55 eva-00 gnome-shell[7226]: JS ERROR: TypeError: this.tip_labels[i] is undefined
                                          update@/home/ahmed/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/extensions/system-monitor@paradoxxx.zero.gmail.com/extension.js:925:56

**Comment by mcardillo55** [comment]
Looks like this is coming from the following exception:
JS ERROR: Extension system-monitor@paradoxxx.zero.gmail.com: Error: Tried to construct an object without a GType; are you using GObject.registerClass() when inheriting from a GObject type?

It looks like it's stemming from checks that were introduced by gjs. There is more discussion and proposed fixes in the thread and comment linked: https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/issues/551#issuecomment-558302621

**Comment by mcardillo55** [comment]
Opened a PR. Works for me on 3.36. Would appreciate feedback on 3.36 and previous versions.

**Comment by mcardillo55** [comment]
Sorry, did not realize PR #564 was already open. That one works for me as well.

**Comment by Kerrung** [comment]
Still doesn't work with GNOME Shell 3.36.0 on Arch Linux... When it be changed?

**Comment by nemoload** [comment]
@Kerrung It's not merged it but you can build it yourself from PR #564

**Comment by Kerrung** [comment]
> @Kerrung It's not merged it but you can build it yourself from PR #564

But, when it will be merged?

**Comment by leinardi** [comment]
Is this project abandoned? Last commit was on November 2019...

**Comment by will-ca** [comment]
@leinardi It's still quite alive AFAICT. The core developers seem to be taking their time to prioritise stability and quality over pushing out a release ASAP.

**Comment by will-ca** [comment]
@leinardi It's still quite alive AFAICT. The core developers seem to be taking their time to prioritise stability and quality over pushing out a release ASAP.

**Comment by leinardi** [comment]
@will-ca prioritize stability and quality is not against the release of an hotfix for a critical bug that make the plugin crash on every recent Linux distribution.

**Comment by ciltocruz** [comment]
Hello.
I have updated to ubuntu 20.04 with GNOME 3.36.1 and I get the same error.

The extension does not load.

As @leinardi says, stability does not mean not releasing new versions. Ubuntu focal has been in testing for months.

Thanks and regards.

**Comment by jeantil** [comment]
I updated to ubuntu 20.04 git  GNOME 3.36.1 recently and I had the same error.  The discussion on the merge request #564  mentioned issues with version 38,  a quick check in ~/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/metadata.json showed I had version 39 installed
After restarting the laptop the extension showed up. (I think restarting gnome shell would have been enough)

**Comment by aluedtke7** [comment]
I can confirm, that a reboot of my Ubuntu 20.04 convinced the extension to show up.

**Comment by Natim** [comment]
Alt+F2 → r

**Comment by Kerrung** [comment]
> Alt+F2 → r

And it doesn't work on Wayland

**Comment by RavanH** [comment]
Just pitching in, adding to the confusion: latest version running on Gnome Shell 3.36.1 (Ubuntu 20.04) does not work in Xorg but on a Wayland session the applet works just fine... Very strange. Let me know if any data needed for debugging :)

**Comment by jeantil** [comment]
hmm RavanH, have you tried the reload/reboot ? 

 I do have the monitors available on an X11 session: 
```
> cat /etc/lsb-release                                                                                                                                                                 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04 LTS"
> env  | grep XDG_SESSION_TYPE                                                                                                                                                         XDG_SESSION_TYPE=x11
>  gnome-shell --version                                                                                                                                                               
GNOME Shell 3.36.1
```

**Comment by RavanH** [comment]
@jeantil in the default (Xorg) session I tried `Ctrl+F2, r` but that did not change anything. Nor did logout/in or even a full reboot.

**Comment by jeantil** [comment]
can you make sure you have version 39+ ?
```
> grep '"version":'  ~/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/metadata.json   
"version": 39
```
note that depending on how the plugin is installed on your system the actual path could vary

**Comment by RavanH** [comment]
Yes, it sais 39 :)
`
~$ grep '"version":'  ~/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/metadata.json
  "version": 39
`

**Comment by nemoload** [comment]
After upgrading and restarting gnome everything seems to work fine now.

**Comment by alexsmithbr** [comment]
Just to add some information for Ubuntu 20.04 newcomers like me: `killall -3 gnome-shell` restarted gnome-shell with system-monitor icons showing properly. No system restart needed. The entire procedure I used was:
```
sudo apt install gnome-shell-extension-system-monitor
gnome-extensions enable system-monitor@paradoxxx.zero.gmail.com
killall -3 gnome-shell
```
All good.
