### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by hadim** [paradoxxxzero/gnome-shell-system-monitor-applet#580]
Can a new version be released and uploaded on https://extensions.gnome.org/, please? So it works on the latest Ubuntu.

**Comment by perebalazs** [comment]
+1

**Comment by hadim** [comment]
Sorry for pinging @franglais125 and @shemgp but I have installed this extension manually using git:

```
git clone https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet.git
cd gnome-shell-system-monitor-applet/
make install
```

and it works well from `master` but when I reboot, gnome tries to update the extension from the gnome repo and then the extension is disabled since it raises an error. So I have to reinstall it manually each time I reboot.

Let me know if I can help with anything in order to make the release process smoother for you.

(using Ubuntu 20.04)

**Comment by hadim** [comment]
(or maybe you know a trick to disable automatic extension update?)

**Comment by franglais125** [comment]
@hadim Yes, this new behaviour is a bit annoying to be honest.

A trick is to artificially increase the version number in the metadata. In the following installation script, I added that modification to have a version number of `100`. Then gnome-shell will see you have no updated needed.

```
git clone https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet.git
cd gnome-shell-system-monitor-applet/
sed -i 's/"version": -1/"version": 100/' system-monitor@paradoxxx.zero.gmail.com/metadata.json
make install
```

**Comment by soaringowl2145** [comment]
When this issue is solved can we please upload it to the ubuntu universe repo so that we can let our system pull all updates from the same place and not rely on gnome/3rd party repos? 

Thanks!

**Comment by p91paul** [comment]
I have a guess: some versions ago, a notification popup suggesting extensions updates was added, and it was controlled by an option in the gnome-shell browser extension. Could you try checking for something like "Check for gnome shell extensions updates" in your browser extension preferences? Maybe now if that check is enabled, auto-update follows.
Otherwise it's most likely gnome-software's fault.
I have that option at off, and gnome-software is not installed, and I don't have automatic updates. So I'm guessing it's one of the two things...

**Comment by p91paul** [comment]
> When this issue is solved can we please upload it to the ubuntu universe repo so that we can let our system pull all updates from the same place and not rely on gnome/3rd party repos?
> 
> Thanks!

I believe for that to happen an ubuntu developer/maintainer has to step up and package this. Not everyone can upload stuff to ubuntu repos. However I think you can open an ubuntu bug to ask them to package this...but I doubt they are going to take care of fixing compatibililty issues for newer shell versions, if upstream gets broken they will probably drop the package instead.

**Comment by franglais125** [comment]
@p91paul It's a built-in "feature".

See here: https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2514

I hope a setting for disabling this will be added soon. I'm astounded that such a thing is on by default.

**Comment by p91paul** [comment]
Yet, I'm on Arch Linux with gnome-shell 3.36 and automatic updates are not happening to me. So there is something that blocks this unwanted behavior, we just don't know what that is.

**Comment by franglais125** [comment]
@p91paul Perhaps it's the way you are installing? `make install` alone does not trigger the `sed` command in the `Makefile` script. Perhaps that's what we need to fix...

What do you see for this?
`cat .local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/metadata.json  | grep version`

The `Makefile` script used to change the version string to the latest commit when using `make install`. I lost track of changes there...

**Comment by p91paul** [comment]
my version there is -1.
Also, I'm not installing through make install, I just made a symlink to my git clone. It's not just this extension, I have four others installed from git. Visiting https://extensions.gnome.org/local/, all 5 of them show an update is available, including this one. None of them is auto-updating.

**Comment by GuessWhatBBQ** [comment]
> @hadim Yes, this new behaviour is a bit annoying to be honest.
> 
> A trick is to artificially increase the version number in the metadata. In the following installation script, I added that modification to have a version number of `100`. Then gnome-shell will see you have no updated needed.


How about just making the version number 100 (or any other arbitrary large number) the default in the master branch as it should always be ahead in terms of patches and features from the released versions,and also because I doubt the autoupdate "feature" is going away any time soon.

**Comment by GuessWhatBBQ** [comment]
> A trick is to artificially increase the version number in the metadata. In the following installation script, I added that modification to have a version number of `100`. Then gnome-shell will see you have no updated needed.


How about just making the version number 100 (or any other arbitrary large number) the default in the master branch as it should always be ahead in terms of patches and features from the released versions,and also because I doubt the autoupdate "feature" is going away any time soon.

**Comment by David-UPCT** [comment]
> @p91paul Perhaps it's the way you are installing? `make install` alone does not trigger the `sed` command in the `Makefile` script. Perhaps that's what we need to fix...
> 
> What do you see for this?
> `cat .local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/metadata.json | grep version`
> 
> The `Makefile` script used to change the version string to the latest commit when using `make install`. I lost track of changes there...

I'm also using archlinux and I've installed the AUR package by means **makepkg** (see https://wiki.archlinux.org/index.php/Arch_User_Repository#Installing_packages). My **metadata.json** file is

```
{
    "shell-version": ["3.26", "3.28", "3.30", "3.32", "3.34", "3.36"],
    "uuid": "system-monitor@paradoxxx.zero.gmail.com",
    "name": "system-monitor",
    "url": "https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet",
    "description": "Display system informations in gnome shell status bar, such as memory usage, cpu usage, network rates…",
    "settings-schema":  "org.gnome.shell.extensions.system-monitor",
    "gettext-domain": "system-monitor",
    "version": -1
}
```
Same behaviour as @p91paul : **system-monitor** is marked in my https://extensions.gnome.org/local/ as updatable, but it doesn't auto-update. 

I hope this info helps.

**Comment by franglais125** [comment]
@p91paul and @David-UPCT Finally had time to look into this.

This is the source of my problem with automatic updates:
https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/master/js/ui/extensionDownloader.js#L110

On Arch, there is perhaps something that is missing, and the condition `if (!Main.extensionManager.updatesSupported)` is triggered, and the whole update is terminated.

Here: https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2514 Florian mentioned that can remove this feature by uninstalling the extensions tool (new in 3.36). In Debian world, this package is called "gnome-shell-extension-prefs" (https://packages.debian.org/unstable/gnome-shell-extension-prefs).

Is there an Arch equivalent for this? I see that the binary is provided by the gnome shell package (`usr/bin/gnome-shell-extension-prefs`). Can you run that?


@GuessWhatBBQ If we set the version number to 100, then users which need an actual upgrade won't get notified.

**Comment by franglais125** [comment]
Sure enough, I purged this package on Debian and the problem is gone. But now I have no access to settings. Again, not a 'feature' in my book. I'll reinstall it, and change the version number for my extensions. You guys got lucky on Arch, for some reason. But careful, it might come and bite you at some point.

**Comment by AllesMeins** [comment]
Could anybody help me to assess the situation here? :-) Should I install the update this way or will it be uploaded to the gnome repository in the foreseeable future? I don't want to miss out on coming updates and don't mind waiting a bit - but it would be nice to know if we're speaking days, weeks. months or never. So what does the decision to push an "official update" depend from?

**Comment by shemgp** [comment]
Found a way to disable auto updates of extensions:
```
chmod -w ~/.local/share/gnome-shell/extension-updates
```
`-w` disables write to the update folder, so no update will happen :grinning:

**Comment by p91paul** [comment]
@franglais125 I can run the new "Extensions" tool. It's pretty mandatory since they removed the extensions preferences from the tweak tool... So maybe Arch configured something different to stop autoupdates.

**Comment by shemgp** [comment]
@p91paul I installed Arch the other day to test this extension and it was the only distro that I used that was having extension autoupdates. So it does work for Arch, not just for you :smile:.

Then I upgraded my Mom's laptop to Ubuntu 20.04 and it did the autoupdate too, all the while in my laptop (Ubuntu 20.04 also) it doesn't. That's how I thought about the `chmod` workaround.

Weird, on some it works, on some it doesn't.

**Comment by medovina** [comment]
@shemgp That is a clever trick with chmod!  I'm running Ubuntu 20.04 and with that trick gnome-shell can no longer clobber my working install of this extension.  Nice!

**Comment by silentjay** [comment]
Anyone wanting to get this up and running on 20.04 needs to install manually as @hadim mentioned, will save you an hour of head scratching:

`git clone https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet.git
cd gnome-shell-system-monitor-applet/
make install`

**Comment by silentjay** [comment]
I'll also add to @shemgp comment on ubuntu 20.04 you need to run `chmod -w ~/.local/share/gnome-shell/extension-updates` before you install system-monitor not after, otherwise a crash happens during your next login, I assume due to the pending update.

**Comment by chrisspen** [comment]
I'll be releasing a new version. Only holdup seems to be the `po/nl_Nl` translation is malformed, and throws the error `msgfmt: error while opening "./nl_NL//system-monitor.po" for reading: No such file or directory` when I create the package. This translation to have been added last July, so I'm not sure why it's failing now.

@Vistaus Any thoughts? Otherwise I'm going to have to delete your translation.

**Comment by chrisspen** [comment]
Nevermind. It looks like the translation files were simply misnamed.

**Comment by chrisspen** [comment]
I've uploaded a release to EGO for review.

**Comment by p91paul** [comment]
@chrisspen Great job!

**Comment by alexeymuranov** [comment]
> @hadim Yes, this new behaviour is a bit annoying to be honest.

Does anybody know where to report this bug/misfeature of GNOME Shell 3.36?
