### ISSUE TITLE
Extension failed to load on gnome 3.36.2

### ISSUE THREAD

**Issue by prhmnik** [paradoxxxzero/gnome-shell-system-monitor-applet#611]
![Screenshot from 2020-05-14 09-25-35](https://user-images.githubusercontent.com/24257037/81896987-e4a25e00-95ca-11ea-8e86-de303eb20e8b.png)

Debian 10 Sid

**Comment by dpriedel** [comment]
I had the same problem with Manjaro Testing when it went to gdm 3.36.2.

I found a solution.

Somehow, my system got reset to use the 'C' locale.  Once I set it back to UTF-8, this extension loads and runs correctly

**Comment by blaze33** [comment]
Had the same issue after upgrading Ubuntu and setting back the locale to UTF-8 worked.
cf. https://askubuntu.com/q/89976/7567

**Comment by prhmnik** [comment]
I'm already the locale to UTF-8 but my problem is not solved.

**Comment by mike-lawrence** [comment]
I'm also already on UTF-8:
![Screenshot from 2020-06-06 13-58-48](https://user-images.githubusercontent.com/150781/83950065-56527e00-a7fe-11ea-825f-ca11693bfda0.png)

but getting the same error:
![Screenshot from 2020-06-06 14-01-33](https://user-images.githubusercontent.com/150781/83950069-5a7e9b80-a7fe-11ea-8019-5262c8256d16.png)

I did just now update from 19.10 to 20.04. Could that be related?

**Comment by supercom32** [comment]
Installed Ubuntu 20.04 LTS which has Gnome 3.36.2 and I can also confirm that this is broken, even with proper locals set. Hopefully someone knows how to resolve this issue.

**Comment by semteXKG** [comment]
same here. already on UTF-8 & ubuntu 20.04 and same error. Which is a shame as this plugin was the best by far...

**Comment by markroxor** [comment]
COPY-PASTING 

@dpriedel 's solution worked for me!! Here is a wrapper for the solution
create file named locale.txt and set it's contents as - 
```shell
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

then run 
```shell
for l in $(cat locale.txt)
do
sudo update-locale $l
done
```

Log out and log back in to find the system monitor extension back. :)

**Comment by semteXKG** [comment]
did not work, switching to the system-monitor-next project did the trick.

**Comment by chfritz** [comment]
It seems that restarting gnome (alt-f2, then run 'r' as the command to run and hit enter) is enough. In my case the locale was OK, but I was missing some dependencies.

**Comment by finsterwalder** [comment]
Could it be, that the locales should not have quotes around them?
I had some locales with and some without quotes. Now I removed all quotes and it works.
I'm not 100% sure that I didn't change anything else.

**Comment by jvanheugten** [comment]
Restarting gnome like @chfritz said worked for me.
