### ISSUE TITLE
Thermal Sensor select is reseted when I reboot my linux.

### ISSUE THREAD

**Issue by Nevuly** [paradoxxxzero/gnome-shell-system-monitor-applet#615]
I using Debian Bullseye (testing branch), I always using this extension in my linux, and I found a new bug.

I set my thermal sensor to Pch_skylake - Temp1, and I reboot my linux.
And I login it again, thermal sensor select is reset, I need to select again.

It is Debian gnome-shell bug or extension bug?

**Comment by PiotrDabrowskey** [comment]
I have exactly the same problem on Ubuntu 20.04 and also identical issue with fan speed.

It doesn't matter if I set `Pch_cannonlake - Temp1` or `Coretemp - Temp1` for the thermal or whatever sensor for the fan, after reboot it always get reset to the unset state and shows `-°C` and `0 rpm`.

I use:
- GNOME System Monitor 3.36.0
- GNOME Shell 3.36.4
- Ubuntu 20.04.1 LTS
- Linux 5.4.0-51-generic

**Comment by PiotrDabrowskey** [comment]
This may be related to https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/issues/381, an old issue from 2017. Yet, it is still open and unsolved.

**Comment by entodoays** [comment]
I don't know if it is related to #615. I don't have to change anything is the extension preferences for it to start working. All I need to do is open the preferences and close the dialog box again.

**Comment by PiotrDabrowskey** [comment]
@entodoays sure, my mistake - sound like a different issue then.

**Comment by Nevuly** [comment]
Well, I think This bug only have debian based linux.

I moved my linux environment to Arch Linux, This problem was fixed.

Maybe, system-monitor extension libraries issue (old version of issue...? maybe...)

**Comment by mopore** [comment]
Hmm... I have the same issue. Running 5.9.3-1-MANJARO

**Comment by ixevix** [comment]
I have this issue sometimes on archlinux
