### ISSUE TITLE
Broken icon with GNOME ≥ 3.32

### ISSUE THREAD

**Issue by jtojnar** [paradoxxxzero/gnome-shell-system-monitor-applet#622]
It was removed: https://github.com/GNOME/adwaita-icon-theme/commits/master/Adwaita/scalable/apps/utilities-system-monitor-symbolic.svg

**Comment by DevDef** [comment]
It could be easily fixed by using the GNOME system monitor icon (`/usr/share/icons/hicolor/symbolic/apps/org.gnome.SystemMonitor-symbolic.svg`) :

```JS
        this.actor = new St.Icon({
            icon_name: 'org.gnome.SystemMonitor-symbolic',
            style_class: 'system-status-icon'
        });
```

**Comment by jtojnar** [comment]
Fixed by https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/commit/6ab4b8e40b7be0cce4502c98f7732450c60461f7
