### ISSUE TITLE
Is there a way to display the system monitor on my lock screen?

### ISSUE THREAD

**Issue by venteto** [paradoxxxzero/gnome-shell-system-monitor-applet#624]
There's a very minimal top bar with the basic Gnome widget with the power/volume/network/night light icons at the top right of the lock screen, so I wondered if there is an existing configuration setting I can fiddle with to make the system monitor extension also appear next to it, or if not, if it could possibly be a new feature in a future version.

There's not a whole lot I need on my lock screen, but this would be particularly useful, especially if it's taking awhile to unlock after coming back to my computer (if my RAM was maxxed out and I was using a lot of swap, for instance, I might just automatically reboot w/o even thinking much more about it).

**Comment by franglais125** [comment]
Like this:

https://github.com/franglais125/gnome-shell-system-monitor-applet/commit/2f5e3fd8bd60c5a184e61fa626263fee493b3a21

**Comment by derrgill** [comment]
Ah so that would be against GNOME guidelines. That's unfortunate. It'd be nice if GNOME would just give a user the option to display basic RAM/swap/et al usage on the lock screen itself without any extension.

**Comment by ZimbiX** [comment]
Related: https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/issues/329

**Comment by venteto** [comment]
@ZimbiX I cloned your fork and it seems to work the way I was originally requesting, so I am reopening this issue for the upstream repo.

As an aside, I think I missed something along way (when this upstream repo was still working) ... what is the "solar" section for?
