### ISSUE TITLE
No NVidia GPU Status (gpu_usage.sh is working)

### ISSUE THREAD

**Issue by ooobii** [paradoxxxzero/gnome-shell-system-monitor-applet#625]
Hi! I'm using Ubuntu 20.04 on the latest kernel with Gnome version 3.36.4 on extension version 39 (according to metadata.json).

I noticed that there were other posts concerning the integrity of the `gpu_usage.sh` file, but after executing this script in the terminal, I do see the 3 values needed by the monitor extension to print these values. After enabling the GPU monitor, nothing appears in the values (Not `NaN`, just blank!)

Any advice would be appreciated, I know that this extension hasn't had a release in a while (:

**Comment by ooobii** [comment]
Well, I'm not sure how and i'm rather embarrassed, but I've gotten the stats to appear by overwriting the `gpu_usage.sh` file on my machine with the contents of the same file located here on the master branch... :smile:

**Comment by pi43r** [comment]
Thanks for the hint. The installed `gpu_usage.sh` was indeed different from the one in the repository.
https://www.diffchecker.com/TIm3ajBI

Still no luck for me with Nvidia MX150 and 460.80 proprietary drivers. Shell executes properly (both versions), but nothing in the monitor.
