### ISSUE TITLE
GNOME Shell 3.38.3 missing

### ISSUE THREAD

**Issue by crysman** [paradoxxxzero/gnome-shell-system-monitor-applet#665]
Default latest _POP OS!_'s GNOME Shell (3.38.3) is not listed in downloads here https://extensions.gnome.org/extension/120/system-monitor/ - which version shall be installed, then?
```
$ gnome-shell --version
GNOME Shell 3.38.3
```

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Pop
Description:	Pop!_OS 20.10
Release:	20.10
Codename:	groovy
```

**Comment by DevDef** [comment]
I hope a new version will be published in the coming weeks. You can see that there are new commits to fix various things.
If you need this extension right now, you’ll have to get the latest code and build it by yourself.

**Comment by crysman** [comment]
if it's coming, I'll wait, thank you

**Comment by chrisspen** [comment]
I'd recommend installing from the master branch using the git checkout procedure in the "Manual installation" section of the README.

There are so many different distros and versions of GNOME out there that I'm hesitant to immediately publish any fixes until I get feedback from some users that everything looks good.

**Comment by crysman** [comment]
@chrisspen OK, I'll do that testing for you and the community, then! (and let you know the results)

**Comment by p91paul** [comment]
not sure if there are more recent fixes, but I've been using your extension on 3.38 for months now. IMHO it's difficult to get positive feedback, lack of negative feedback has to be interpreted as ok.

**Comment by crysman** [comment]
OK, no need to test this, because I've just found out that it is in the official repository:

```
$ sudo apt show gnome-shell-extension-system-monitor 
Package: gnome-shell-extension-system-monitor
Version: 38+git20200414-32cc79e-1
Priority: optional
Section: universe/gnome
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Jonathan Carter <jcc@debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 296 kB
Depends: gir1.2-clutter-1.0, gir1.2-gtop-2.0, gnome-shell
Suggests: glxinfo
Homepage: https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet
Download-Size: 47.8 kB
APT-Manual-Installed: yes
APT-Sources: http://us.archive.ubuntu.com/ubuntu groovy/universe amd64 Packages
Description: Display system information in GNOME Shell status bar
 System information such as memory usage, cpu usage, network rates and more
 can be displayed in the notification area in GNOME Shell.
 .
 Settings can be accessed via gnome-tweak-tool where monitoring settings
 can be adjusted.
```

we may close this now, thanks

**Comment by crysman** [comment]
It works quite OK, what is unfortunate is that tooltips are positioned top-left on my screen (using no fancy setup, only one display)... but that is another issue... thanks.

**Comment by DevDef** [comment]
This top-left position bug has already been fixed (3 days ago). Your Debian package needs to be updated. Ask the packager...

**Comment by chrisspen** [comment]
Yeah, I wouldn't rely on any system package. Those are usually very old and out of date.

**Comment by p91paul** [comment]
@chrisspen you can help them with that, by tagging your releases. A good package maintainer would put an automatic trigger on your tags, and keep the package up to date that way.

**Comment by DevDef** [comment]
I’d like to see a new release too. But it would be nice if it’s in the best shape as possible, i.e. with translation updated and all the remaining good suggestions in PRs merged.
