### ISSUE TITLE
Add support for GNOME 40 and an updated version to https://extensions.gnome.org/extension/120/system-monitor/

### ISSUE THREAD

**Issue by Kerrung** [paradoxxxzero/gnome-shell-system-monitor-applet#672]
Add support for GNOME 40 and an updated version to https://extensions.gnome.org/extension/120/system-monitor/

**Comment by p91paul** [comment]
The extension mostly work by just changing version in metadata.json.
Preferences don't, of course, because of the gtk 4 switch.

**Comment by BlackDex** [comment]
Using Arch Linux here.

**Comment by Kerrung** [comment]
> What distro/release is everyone mostly using?

I use Arch Linux (rolling release).

**Comment by ludenticus** [comment]
> What distro/release is everyone mostly using?

Arch Linux user too

**Comment by leogr** [comment]
Arch Linux user

**Comment by d2r2** [comment]
> The extension mostly work by just changing version in metadata.json.
> Preferences don't, of course, because of the gtk 4 switch.

Thanks @p91paul! Helps as a temporary fix, if append "40" to "shell-version": [...] in metadata.json.

**Comment by Arjdroid** [comment]
> What distro/release is everyone mostly using?

Arch Linux (Rolling Release)

I would assume most users with this issue will be Arch Linux or other Rolling Release distro users because other distros like Pop!_OS and Ubuntu are still on GNOME 3.8 with the major exception being Fedora

**Comment by Arjdroid** [comment]
> > The extension mostly work by just changing version in metadata.json.
> > Preferences don't, of course, because of the gtk 4 switch.
> 
> Thanks @p91paul!
> To All. As a temporary partial fix, append `"40"` to `"shell-version": [...]` in metadata.json.
> P.S. The extension is usually located in the folder: `~/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/`

Would I be correct in assuming that this workaround only works for users who already had this extension on their system BEFORE "upgrading" to GNOME 40 because I am on a GNOME 40 Arch Linux system and have tried this workaround to get the manually installed version working but the Extensions App doesn't allow me to switch on the extension and as you have mentioned the Preferences (gear icon button in my case) is not working and give a GTK-related error.

Is there anything I could try to trick the system into running the extension like some sort of file changes and then making Preference changes via some file changes like copying the configuration file from an existing Pop!_OS system running the extension with my desired configuration into the directory where it checks for my preferences? 

Actually, now that I think of it, the Extension might not be allowing me to run it because it can't find it's configuration file.

I will edit this comment in case I somehow get it working on a fresh system.

Thanks in advance.

**Comment by p91paul** [comment]
@Arjdroid manual installation instructions are provided in this repository README.

Also, there might (or not) be an AUR package, which might (or not) be up to date.

**Comment by Arjdroid** [comment]
> @Arjdroid manual installation instructions are provided in this repository README.
> 
> Also, there might (or not) be an AUR package, which might (or not) be up to date.

I'm sorry if my question was not clear, I am already able to install it via make install and it is showing up in the Extensions app but it is not allowing me to enable the Extension for whatever reason. The extension only shows up after appending "40" to the metadata.json file also.

 The AUR version doesn't even show up in the folder for the extensions so there is no metadata.json I can find and it doesn't show up in the Extensions app either.

Also, when opening extensions app, it prompts me to log out to update the system monitor extension and it updates to version 39 when I installed from v38.tar.gz

I theorise that it (the Extensions app) won't let me enable the extension because there is a missing config file although I can't be sure...

**Comment by p91paul** [comment]
@Arjdroid well then you didn't try it recently, because since #678 was merged a few days ago, 40 already is in metadata.json and everything, even the preferences window, should be working out of the box

**Comment by Arjdroid** [comment]
> @Arjdroid well then you didn't try it recently, because since #678 was merged a few days ago, 40 already is in metadata.json and everything, even the preferences window, should be working out of the box

I'm downloading from the releases page on the GitHub and latest over there is v38 from 2019, I haven't tried cloning the repo yet but will do that, thanks!

**Comment by gfoligna** [comment]
Please pin this issue to avoid repeated submissions :smile_cat:

**Comment by Akiyamka** [comment]
It's great to have a workaround, but how about a release?

**Comment by darkdragon-001** [comment]
Please add a release since Gnome Extensions continues to "auto-update" the extension back to the broken one from extensions.gnome.org...

**Comment by Tyr4El** [comment]
what's the status on this ?

**Comment by AlexWayfer** [comment]
@Tyr4El you can see the open issue just above your question:

![image](https://user-images.githubusercontent.com/6510020/119487712-6393b000-bd62-11eb-8c72-0c1a305df61c.png)


With [an answer from owner a week ago](https://github.com/negesti/gnome-shell-extensions-negesti/issues/191#issuecomment-842575810).

So, it looks like not finished yet.

**Comment by p91paul** [comment]
@AlexWayfer That issue is on another repository, for another extension.

For this one, support for Gnome 40 is ready and mainlined, but right now the only option is manual install from git master branch, using the instructions in the README. To avoid automatic updates, just edit metadata.json and add 
```
, "version": "1000"
```
Before the closing }

**Comment by AlexWayfer** [comment]
> @AlexWayfer That issue is on another repository, for another extension.

Oh, my bad, sorry, It seems, I was too tired.

So, then we just wait for a release from @chrisspen (wrote here as a collaborator and merged the fix).

**Comment by gfoligna** [comment]
> What distro/release is everyone mostly using?

Fedora 34

**Comment by LicoMonch** [comment]
> > What distro/release is everyone mostly using?
> 
> Fedora 34

As Fedora 34 user just use the repo as suggested in README.md
Worked for me without problems

**Comment by Jerther** [comment]
@LicoMonch The "Repository installation" suggested in README.md does not work:

```
sudo dnf install gnome-shell-extension-system-monitor-applet

**snip!!**

Installed:
  gnome-shell-extension-system-monitor-applet-1:38-12.20210507gitbc38ccf.fc34.noarch                                    

Complete!

gnome-shell-extension-tool --enable-extension=system-monitor@paradoxxx.zero.gmail.com
gnome-shell-extension-tool is deprecated, use gnome-extensions instead
Extension “system-monitor@paradoxxx.zero.gmail.com” does not exist
```

If you're talking about the **GIT** repository, then it may work indeed, but it's a manual installation and I'd rather wait for a proper Fedora repository update.

**Comment by dreua** [comment]
@Jerther it works fine for me on Fedora 34. Please create a new issue and ping me there, so we can debug your specific issue.

**Comment by darkdragon-001** [comment]
The _repository version_ doesn't work for me:
```
Error: No property border_width on GtkFrame

Stack trace:
  _init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:45:40
  SystemMonitor@/home/mschnirring/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/prefs.js:141:22
  SystemMonitor_App/<@/home/mschnirring/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/prefs.js:295:38
  SystemMonitor_App@/home/mschnirring/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/prefs.js:294:23
  buildPrefsWidget@/home/mschnirring/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/prefs.js:367:18
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
  ```
  
  And when installing from git, it is always updated by _Gnome Extensions_...

**Comment by gfoligna** [comment]
> > > What distro/release is everyone mostly using?
> > 
> > 
> > Fedora 34
> 
> As Fedora 34 user just use the repo as suggested in README.md
> Worked for me without problems

Steps that worked for me:
* Clone this repo from master / download .zip
* cd into `./gnome-shell-system-monitor-applet/system-monitor@paradoxxx.zero.gmail.com`
* Edit `metadata.json` and change `"version": -1` into `"version": 1000`
* `cd ..`
* make install
* Reload Gnome Shell or logout and back in (Wayland)

**Comment by gfoligna** [comment]
@darkdragon-001 See my message above :)

**Comment by Zesko** [comment]
> The _repository version_ doesn't work for me:
> 
> ```
> Error: No property border_width on GtkFrame
> 
> Stack trace:
>   _init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:45:40
>   SystemMonitor@/home/mschnirring/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/prefs.js:141:22
>   SystemMonitor_App/<@/home/mschnirring/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/prefs.js:295:38
>   SystemMonitor_App@/home/mschnirring/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/prefs.js:294:23
>   buildPrefsWidget@/home/mschnirring/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/prefs.js:367:18
>   _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
>   OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
>   asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
>   run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
>   main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
>   run@resource:///org/gnome/gjs/modules/script/package.js:206:19
>   start@resource:///org/gnome/gjs/modules/script/package.js:190:8
>   @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
> ```
> 
> And when installing from git, it is always updated by _Gnome Extensions_...

I have the same issue. I can not open "Preferences".

**Comment by gfoligna** [comment]
After having some mangled characters at the bar by installing it manually I found this as the solution, taking over the place of this extension.
https://extensions.gnome.org/extension/3010/system-monitor-next/

**Comment by chrisspen** [comment]
A new release is now live on extensions.gnome.org.
