### ISSUE TITLE
3.40

### ISSUE THREAD

**Issue by udovdh** [paradoxxxzero/gnome-shell-system-monitor-applet#688]
Gnome 3.40 on Fedora 34 does not display the applet; should this work?

**Comment by p91paul** [comment]
see https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/issues/672 and #678

**Comment by udovdh** [comment]
$ /usr/bin/gjs system-monitor@paradoxxx.zero.gmail.com/extension.js 

(gjs:93007): Gjs-CRITICAL **: 17:05:24.423: JS ERROR: ImportError: No JS module 'misc' found in search path
@system-monitor@paradoxxx.zero.gmail.com/extension.js:29:14

**Comment by udovdh** [comment]
$ gresource list `locate libgnome-shell.so`|grep misc

**Comment by p91paul** [comment]
@udovdh I don't know what you are trying to accomplish with those commands, but AFAIK they are not a way to run any extension.
If you install from current master, it should work on Gnome 40.

**Comment by udovdh** [comment]
We are at git head.
We set disable-extension-version-validation to true.
None of the extensions function.
`gnome-extensions-app dumps core.
gnome-extensions is no replacement for functionality.

**Comment by udovdh** [comment]
> @udovdh I don't know what you are trying to accomplish with those commands, but AFAIK they are not a way to run any extension.

What _is_ the way to run any extension?
I.e.: how can I test to see why the extensions don't run?

**Comment by p91paul** [comment]
@udovdh repository README reports various ways to install this extension, you should look into the manual one.
Basically it's about putting the files in the right directory and enabling the extension from the Extensions tool so that gnome loads it, you don't "run" an extension.
Logs get reported in journalctl if there is any error.

**Comment by udovdh** [comment]
That does not work:
We have the git head version linked to the right spot.
extensions.gnome.org/local does not have effective control over starting.
`gnome-extensions` does not have effective control over starting the extension.
`gnome-extensions-app` dumps core, so does not have effective control over starting the extension.
Journal is another bug.
So how can I see what is wrong?

**Comment by hwlyom** [comment]
Doesn't work on ArchLinux, all software is up to date and packages `libgtop networkmanager gnome-system-monitor` all installed as well.
The extension hasn't worked at all since Gnome upgraded to v40.

**Comment by p91paul** [comment]
There is clearly something wrong with whatever you both are doing, but as you insist on not posting any logs I'm afraid that nobody will be able to help... just wait until extensions.gnome.org is updated, I don't know when the maintainer intends to do so.

**Comment by hwlyom** [comment]
> just wait until extensions.gnome.org is updated, I don't know when the maintainer intends to do so.

This is really important information to know for us not to post any logs while thinking we are doing things correctly as the documentation says. At least from my side I'm following what it's said [here](https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet#browser-installation), If extensions.gnome.org hasn't updated the best thing would be to have it in the documentation saying it, also it may put pressure on them who knows.
> There is clearly something wrong with whatever you both are doing

Strange, I didn't know following the documentation is wrong?
I'll install it manually in that case (I imagine the documentation is correct there)

Anyway, this is a great extension and I don't know why you wouldn't want have it, great work! 💪

**Comment by Bidski** [comment]
```
Error: No property border_width on GtkFrame

Stack trace:
  _init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:45:40
  SystemMonitor@/home/bidski/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/prefs.js:141:22
  SystemMonitor_App/<@/home/bidski/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/prefs.js:295:38
  SystemMonitor_App@/home/bidski/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/prefs.js:294:23
  buildPrefsWidget@/home/bidski/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/prefs.js:367:18
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by hwlyom** [comment]
"it works for me", you might have missed something, mine it works perfectly fine
`"shell-version": [`
`    "3.26",`
`    "3.28",`
`    "3.30",`
`    "3.34",`
`    "3.32",`
`    "3.36",`
`    "40"`
`  ],`

**Comment by Bidski** [comment]
For some reason I downloaded the `38` release rather than master. Settings page works fine now

**Comment by chrisspen** [comment]
A new release is now live on extensions.gnome.org.
