### ISSUE TITLE
UI Docker test does not run from CI

### ISSUE THREAD

**Issue by chrisspen** [paradoxxxzero/gnome-shell-system-monitor-applet#695]
The UI integration test created as part of issue #663 runs fine locally in Docker, but appears to timeout when run from Docker inside either Travis CI or Github CI.

As the entire point of developing that integration test was to quickly build and confirm that PRs don't break basic functionality, this is the last piece remaining and needs to be fixed.

My current attempts to fix this, and diagnose the problem, are committed to the ci_gui branch.

This needs to be fixed, ideally in Travis CI, since that's what we've been using to run builds. However, if for some reason Travis CI just doesn't support all the Docker features necessary to run our image, getting it working in Github CI instead is acceptable.

I've updated the Travis CI config file to run the Docker tests. I've added a stub Github CI config file `.github/workflows/ci.yml` with what I think should run the test. Both appear to timeout and don't even write the log file `/home/default/shared/stdout.log` output in `docker/ubuntu/startx`, which leads me to suspect there might be a file systems permission issue.

The `startx` script is the cornerstone to the entire test. It's what launches the Gnome environment with `dbus-launch --exit-with-session gnome-session`, but before doing so, it launches the `testing/run_gui_tests` script with nohup. When testing locally, it has to be done that in that order, since the `dbus-launch` command blocks, and attempting to run that with nohup causes it to fail for a reason I couldn't determine.

When docker launches, through the `docker/run-docker.sh` command, it mounts the local `./testing`, containing the test scripts, as a volume inside the Docker container. This allows the test script to be quickly changed without having to rebuild the entire image. It also allows the script to output and persist a log file from inside Docker, which would otherwise be lost when the container exits. Run the Docker build process locally outputs `testing/stdout.log` and `testing/stderr.log`. However, neither of these files appear to be generated either on Travis or Github CI.

One potential problem is that since the `run_gui_tests` command runs before Gnome launches, it's possible that it tries to access a UI that doesn't exist yet. However, I've added ample waits to the script that should give plenty of time for Gnome to initialize, even on a constrained cloud VM in Travis or Github.

**Comment by braewoods** [comment]
What would need to be done to claim the bounty? Just fix the test's ability to run?

**Comment by chrisspen** [comment]
@braewoods Yes. Confirm the test runs in CI by getting it's status code and output the stdout and stderr logs from the test script, just as it does when run from a Linux localhost.

**Comment by braewoods** [comment]
I believe I've found the culprit. For some reason /home/default/shared is owned by uid/gid 2000 on the docker container created by Travis CI whereas it is owned by default/default in local containers. A chown of /home/default/shared to default:default appears to resolve this issue. How should this be integrated into your existing code? The branch you mentioned seems rather messy and not intended for merging in its current state.

**Comment by braewoods** [comment]
I believe #698 addresses this issue.

**Comment by chrisspen** [comment]
Great. I thought it was probably something super simple, but I wasn't seeing anything.

**Comment by chrisspen** [comment]
@braewoods I've merged your PR. Great job.

**Comment by chrisspen** [comment]
@braewoods Feel free to collect the bounty.

**Comment by braewoods** [comment]
I've been waiting for BountySource to acknowledge that this issue has been closed. That's why I haven't.

**Comment by chrisspen** [comment]
I didn't think you had to wait for the issue to close. I think you just claim the bounty in their UI. Then they ask me to approve it, and I can either approve immediately, or it auto-approves if I don't respond after a certain period of time.

**Comment by braewoods** [comment]
Well I've never seen the bounty claim option appear until after the issue is marked closed on their end. It makes sense why that would be. You don't want to receive frivolous claims before it's been closed.
