### ISSUE TITLE
The repository installation does not work on Fedora 34

### ISSUE THREAD

**Issue by Jerther** [paradoxxxzero/gnome-shell-system-monitor-applet#701]
The "Repository installation" suggested in README.md does not work in Fedora 34:

```
sudo dnf install gnome-shell-extension-system-monitor-applet

**snip!!**

Installed:
  gnome-shell-extension-system-monitor-applet-1:38-12.20210507gitbc38ccf.fc34.noarch                                    

Complete!

gnome-shell-extension-tool --enable-extension=system-monitor@paradoxxx.zero.gmail.com
gnome-shell-extension-tool is deprecated, use gnome-extensions instead
Extension “system-monitor@paradoxxx.zero.gmail.com” does not exist
```

@dreua

Followup to https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/issues/701

**Comment by dreua** [comment]
Thanks!

Can you run `gnome-extensions list`for me?

**Comment by dreua** [comment]
1. And maybe `gnome-extensions enable system-monitor@paradoxxx.zero.gmail.com` just works?
1. Have you done a reboot since installing the extension and tried again? (Or restart X via Alt+F2, r, enter)
2. Are you using X or Wayland?

**Comment by Jerther** [comment]
Sure thing.

```
$ gnome-extensions list

alternate-tab@gnome-shell-extensions.gcampax.github.com
notifications-alert-on-user-menu@hackedbellini.gmail.com
user-theme@gnome-shell-extensions.gcampax.github.com
launch-new-instance@gnome-shell-extensions.gcampax.github.com
window-list@gnome-shell-extensions.gcampax.github.com
mprisindicatorbutton@JasonLG1979.github.io
nohotcorner@azuri.free.fr
vertical-overview@RensAlthuis.github.com
apps-menu@gnome-shell-extensions.gcampax.github.com
background-logo@fedorahosted.org
places-menu@gnome-shell-extensions.gcampax.github.com
pidgin@muffinmad
appindicatorsupport@rgcjonas.gmail.com

$ sudo dnf install gnome-shell-extension-system-monitor-applet

Last metadata expiration check: 1:01:48 ago on Tue 06 Jul 2021 08:28:21 AM.
Dependencies resolved.
========================================================================================================================
 Package                                          Arch        Version                                Repository    Size
========================================================================================================================
Installing:
 gnome-shell-extension-system-monitor-applet      noarch      1:38-12.20210507gitbc38ccf.fc34        updates       77 k

Transaction Summary
========================================================================================================================
Install  1 Package

Total download size: 77 k
Installed size: 272 k
Is this ok [y/N]: y
Downloading Packages:
gnome-shell-extension-system-monitor-applet-38-12.20210507gitbc38ccf.fc34.noarch.rpm    321 kB/s |  77 kB     00:00    
------------------------------------------------------------------------------------------------------------------------
Total                                                                                   111 kB/s |  77 kB     00:00     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                1/1 
  Installing       : gnome-shell-extension-system-monitor-applet-1:38-12.20210507gitbc38ccf.fc34.noarch                                                                                                                                   1/1 
  Running scriptlet: gnome-shell-extension-system-monitor-applet-1:38-12.20210507gitbc38ccf.fc34.noarch                                                                                                                                   1/1 
  Verifying        : gnome-shell-extension-system-monitor-applet-1:38-12.20210507gitbc38ccf.fc34.noarch                                                                                                                                   1/1 

Installed:
  gnome-shell-extension-system-monitor-applet-1:38-12.20210507gitbc38ccf.fc34.noarch                                                                                                                                                          

Complete!

$ gnome-extensions list

alternate-tab@gnome-shell-extensions.gcampax.github.com
notifications-alert-on-user-menu@hackedbellini.gmail.com
user-theme@gnome-shell-extensions.gcampax.github.com
launch-new-instance@gnome-shell-extensions.gcampax.github.com
window-list@gnome-shell-extensions.gcampax.github.com
mprisindicatorbutton@JasonLG1979.github.io
nohotcorner@azuri.free.fr
vertical-overview@RensAlthuis.github.com
apps-menu@gnome-shell-extensions.gcampax.github.com
background-logo@fedorahosted.org
places-menu@gnome-shell-extensions.gcampax.github.com
pidgin@muffinmad
appindicatorsupport@rgcjonas.gmail.com

$ gnome-extensions enable system-monitor@paradoxxx.zero.gmail.com

Extension “system-monitor@paradoxxx.zero.gmail.com” does not exist

```

I haven't tried a reboot yet. Will do after this post.

Using Wayland

**Comment by Jerther** [comment]
No way.... I rebooted, did `gnome-extensions enable system-monitor@paradoxxx.zero.gmail.com` and the thing started...

Having to reboot was the usual thing to do back in 1997 but it has become a rare thing in late years. I think I may have become a bit spoiled ;)

By the way I really did a reboot. I did not try to log out and back in but that might have worked too and it would make sens.

**Comment by dreua** [comment]
Meh, so this is another one of the Wayland hurdles. I'm still with X by the way... You are right, reboot should not be necessary but at the end of the day, it is the way to make absolutely sure that everything is reloaded. With X `Alt+F2, r` works fine, I don't know the equivalent Wayland commands unfortunately.

**Comment by Jerther** [comment]
Well I don't install this extension every day so I can live with that.

For now... ;)

Should I close this issue?

**Comment by dreua** [comment]
Yes, this issue sounds closed to me.

Wayland/Gnome really needs a better way to handle this but that is another topic, not specific to the system-monitor-applet. Happy monitoring! :tada:

**Comment by p91paul** [comment]
@dreua there is not an equivalent unfortunately. alt-f2+r just doesn't work, and apparently there isn't a way to make it work.
AFAIK with X your windows, and gnome shell itself, all use X for drawing, so you can restart the gnome-shell process without killing everything else.
With wayland instead the shell also acts like a compositor for all other windows. So there is no way to safely restart the shell without also killing all of the user processes.

My explanation is probably quite inaccurate because I don't have a very good understanding of neither wayland nor X, but that's what I got when I was googling how to restart the shell on wayland a while ago. It's a PITA when you are debugging extensions.

**Comment by dreua** [comment]
@p91paul I think you got that right, I also understand it like you said. I'm wondering: Is it to be fixed in Wayland or in Gnome? Any open Bugs already?

**Comment by p91paul** [comment]
@dreua I believe it's in gnome, they would need to implement a way to reload extensions without restarting the whole gnome-shell process.

Apparently it was reported, but closed without leaving hope for a fix.
https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/1011
