### ISSUE TITLE
No longer works on ubuntu 20.04

### ISSUE THREAD

**Issue by matteosal** [paradoxxxzero/gnome-shell-system-monitor-applet#705]
The OS installed some updates recently and the extension stopped working for me. I went back to https://extensions.gnome.org/ to uninstall and reinstall but nothing changed.

After reinstallation the webpage shows that the extension is OFF. Clicking on the switch turns it to ON, but after reloading the page it's OFF again.

I can also access the settings window (which is still reporting my settings) by clicking on the blue tools icon (still in the extension webpage), but the indicators are never shown in the status bar.

**Comment by chrisspen** [comment]
Does it work if you install from master?

**Comment by matteosal** [comment]
Never mind, I found the issue. Turns out ALL extensions were somehow disabled by the OS update. This answer 
did the job for me: https://askubuntu.com/a/1202943/595969
