### ISSUE TITLE
Any plans to make new release?

### ISSUE THREAD

**Issue by kloczek** [paradoxxxzero/gnome-shell-system-monitor-applet#706]
I think that it would be good to flush currently committed changes and make new release :)

**Comment by DanieLoche** [comment]
In the meantime, I recommend trying the fork presented in #673 => it's directly a release based on Master.

**Comment by chrisspen** [comment]
A new release is now live on extensions.gnome.org.

**Comment by costela** [comment]
@chrisspen would it also be possible to tag the release here? This would make distro maintainers' lives a bit easier.

**Comment by kloczek** [comment]
Still last version is v38 :/
