### ISSUE TITLE
App not working on ubuntu 20.04.02 LTS

### ISSUE THREAD

**Issue by silencify** [paradoxxxzero/gnome-shell-system-monitor-applet#707]
I have run the command. But the applet is not showing up. I was using it in the Ubuntu 18.04 and it was working fine. This is one of the best applet I have used. Thanks.
My system is:

OS Name -  Ubuntu 20.04.2 LTS
OS Type - 64-bit
GNOME Version - 3.36.8
Windowing System X11

**Comment by mhow2** [comment]
I can confirm that. Here is what I can find in system logs when enable the extensions:

`
Aug  5 08:41:25 martin-ThinkPad-T420 gnome-shell[2003]: [System monitor] applet enabling`
`
Aug  5 08:41:25 martin-ThinkPad-T420 gnome-shell[2003]: JS ERROR: Extension system-monitor@paradoxxx.zero.gmail.com: Error: Tried to construct an object without a GType; are you using GObject.registerClass() when inheriting from a GObject type?#012SystemMonitor_smDialog@/home/martin/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/extension.js:286:9#012enable@/home/martin/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/extension.js:2309:23#012_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:167:32#012loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:351:26#012callback@resource:///org/gnome/shell/ui/extensionDownloader.js:234:39#012gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:115:13
`

**Comment by chrisspen** [comment]
This seems to be a bug in the code that breaks the extension when Wayland's enabled. I was able to get the extension to work in 20.04 by disabling Wayland, rebooting, and then checking out the repo and running `make install`, followed by a `alt+f2 r`to reload.

That's not an ideal solution, but that's one workaround for now.

**Comment by Nhat-Thanh** [comment]
26/01/2022

I'm also using Ubuntu 20.04 LTS, I install libgtop2-dev package and it fixed this error at all

**Comment by tejaskale** [comment]
FYI : after installing required libraries,  logout and back in ( especially  if you are using wayland ; "r" might work on X11 ) to properly restart gnome-shell.

**Comment by silencify** [comment]
@chrisspen Thanks it the issue. Please refer https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/issues/707#issuecomment-980459788

**Comment by mbana** [comment]
> 26/01/2022
> 
> I'm also using Ubuntu 20.04 LTS, I installed libgtop2-dev package and it fixed this error at all

Same here.

On Ubuntu 22.04.1 under Wayland installing `libgtop2-dev` did the trick:

```sh
sudo apt-get install gir1.2-gtop-2.0 gir1.2-nm-1.0 gir1.2-clutter-1.0 gnome-system-monitor gir1.2-gtop-2.0 gir1.2-nm-1.0 gir1.2-clutter-1.0 gnome-system-monitor gir1.2-gtop-2.0 gir1.2-nm-1.0 gnome-system-monitor libgtop2-dev
```

**Comment by pabloab** [comment]
`apt install libgtop2-dev` worked under Pop 22.04 **with x11**, using mgalgs's [fork](https://extensions.gnome.org/extension/3010/system-monitor-next/).
