### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by BloodyIron** [paradoxxxzero/gnome-shell-system-monitor-applet#710]
So is this extension abandoned?

**Comment by p91paul** [comment]
Well last commit is less than 2 weeks old, so I'd say it's not abandoned.

**Comment by BloodyIron** [comment]
Last release April 2019, doesn't even have GNOME 40 support, let alone 41.

So...? Abandoned-ish.

**Comment by p91paul** [comment]
It's just not updated on extensions.gnome.org, there are already opened issues for that. On this repository the master branch fully supports Gnome 40. Follow manual installation instructions.

**Comment by BloodyIron** [comment]
No, I'm talking about the release section of _this github project_ has a last release date of April 2019. Can we get a new release and update on the extensions page already please?

**Comment by p91paul** [comment]
I think this issue can be closed as duplicate of  https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/issues/706, https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/issues/672 and others

**Comment by gfoligna** [comment]
I guess this has been fixed by https://extensions.gnome.org/extension/3010/system-monitor-next/

**Comment by chrisspen** [comment]
A new release is now live on extensions.gnome.org.
