### ISSUE TITLE
Support GNOME 41

### ISSUE THREAD

**Issue by marxin** [paradoxxxzero/gnome-shell-system-monitor-applet#717]
After updating to Gnome 41, I see the following error:
`Gtk.VBox is not a constructor`. Which is likely related to fack that `VBox` is deprecated:
https://docs.gtk.org/gtk3/class.VBox.html

**Comment by marxin** [comment]
The error is strange as it's guarded in `if (shellMajorVersion < 40) {`

 https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/blob/133f9f32bca5d159515d709bbdee81bf497ebdc5/system-monitor%40paradoxxx.zero.gmail.com/prefs.js#L144-L151

**Comment by marxin** [comment]
Oh, so one only needs adding `41` to `shell-version`.

**Comment by freddyw** [comment]
Fedora 35 was released today so I would like this merged as well.
