### ISSUE TITLE
Gnome 40 - refreshing issue

### ISSUE THREAD

**Issue by pstolarz** [paradoxxxzero/gnome-shell-system-monitor-applet#720]
After upgrading to Gnome 40 I observe some refreshing issue withing the extension canvas. It looks like this (photo taken by a phone): ![Screenshot from 2021-10-16 14-00-32](https://user-images.githubusercontent.com/10219177/137586679-334661d8-8bb1-4d19-b6cb-3c50055488ab.png)

Unfortunately, it is not possible to make a screenshot, since in the moment of taking it the screen is refreshed and the garbage disappears.

**Comment by bobzurad** [comment]
I'm seeing the same issue on Pop!_OS 21.10, which is currently using Gnome 40.4.0

![PXL_20211222_173110544 MP](https://user-images.githubusercontent.com/408733/147132969-b546c090-6f27-42f5-a81e-3e40702eb7e6.jpg)

It looks like for digits, only some of the pixels on the right are refreshing.

**Comment by scr4bble** [comment]
Same issue here:
Fedora 34 (xorg)
GNOME Shell 40.6

**Comment by felipebutcher** [comment]
Same issue here:
Ubuntu 21.10
GNOME 40.4.0

**Comment by felipebutcher** [comment]
Same issue here:
Ubuntu 21.10
GNOME 40.4.0

**Comment by bobzurad** [comment]
Upgrading to Pop!_OS 22.04, which uses Gnome 42, fixed this issue for me. 

However, with Gnome 42, I had to switch to the "next" version: https://extensions.gnome.org/extension/3010/system-monitor-next/
