### ISSUE TITLE
"Tried to construct an object without a GType" when trying to install on Pop!_OS 21.10

### ISSUE THREAD

**Issue by jamie-pate** [paradoxxxzero/gnome-shell-system-monitor-applet#738]
I'm unable to install this extension on Gnome 40.6 on Pop!_OS 21.10 because of this error

The error that shows in the gnome `Extensions` app `Tried to construct an object without a GType`

```
Mar 18 10:53:14 ca-200937-nb1 gnome-shell[3325]: [System monitor] applet init from /home/jpate/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com
Mar 18 10:53:14 ca-200937-nb1 gnome-shell[3325]: [System monitor] applet enabling
Mar 18 10:53:14 ca-200937-nb1 gnome-shell[3325]: JS ERROR: Extension system-monitor@paradoxxx.zero.gmail.com: Error: Tried to construct an object without a GType
                                                 SystemMonitor_smDialog@/home/jpate/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/extension.js:287:9
                                                 enable@/home/jpate/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/extension.js:2410:23
                                                 _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:168:32
                                                 loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:351:26
                                                 callback@resource:///org/gnome/shell/ui/extensionDownloader.js:241:39
                                                 gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:115:13
```

**Comment by jrdmellow** [comment]
I had this as well when first installing. Make sure you follow the [Installation](https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet#installation) section in the readme.

It's unfortunate that the dependency has to be manually installed. Perhaps it should be clearer in the extension description that dependencies are required. Best case would be catching the error and displaying something right in the status bar.

**Comment by jamie-pate** [comment]
The following NEW packages will be installed:
  gir1.2-clutter-1.0 gir1.2-cogl-1.0 gir1.2-coglpango-1.0 gir1.2-gtop-2.0
  
  Maybe it changed at some point when I updated the system or when the extension updated
  
  Worked after installing the dependencies from the readme and restarting gnome (alt-f2 then r)
