### ISSUE TITLE
Port the Fedora package to Debian (deb)

### ISSUE THREAD

**Issue by FranklinYu** [paradoxxxzero/gnome-shell-system-monitor-applet#742]
The extension has several dependencies, as noted in the ReadMe. It would be more convenient for users if they can install this extension via `apt`, which keeps track of the dependencies automatically. Fedora already has [a package](https://src.fedoraproject.org/rpms/gnome-shell-extension-system-monitor-applet); might be worth submitting a Debian package to the Debian team.

<sub>I might take a look at this later this year, but don’t rely on it. Any one feel free to work on it.</sub>
<sub>suggest label: feature request</sub>

**Comment by FranklinYu** [comment]
Thank you. The Debian package does the job very well; shall we add it to the “repository installation” section in ReadMe?

**Comment by mgalgs** [comment]
@matheuswillder FYI the [system-monitor-next](https://github.com/mgalgs/gnome-shell-system-monitor-next-applet) fork of this extension (which is what the Fedora package now points to) uses a new name and thus shouldn't conflict with the official GNOME extension.
