### ISSUE TITLE
Error after 22.04 today upgrade

### ISSUE THREAD

**Issue by mcastagnaa** [paradoxxxzero/gnome-shell-system-monitor-applet#750]
![image](https://user-images.githubusercontent.com/4532767/188265155-81166621-b9e8-490b-917f-e476b86b947d.png)

**Comment by bmaupin** [comment]
You're probably missing a dependency; try this:

```
sudo apt install gir1.2-gtop-2.0
```

This is more or less a duplicate of #737. You'll see a lot more helpful information there.

**Comment by mcastagnaa** [comment]
That did the job! Thank you.
