### ISSUE TITLE
extenstions.gnome.org install error: Your native host connector do not support following APIs: v6

### ISSUE THREAD

**Issue by maksym-arutyunyan** [paradoxxxzero/gnome-shell-system-monitor-applet#763]
After installing the extension from https://extensions.gnome.org/extension/3010/system-monitor-next I'm getting the following error:

> Your native host connector do not support following APIs: v6. Probably you should upgrade native host connector or install plugins for missing APIs. Refer [documentation](https://wiki.gnome.org/Projects/GnomeShellIntegrationForChrome/Installation) for instructions.

Ubuntu 22.04.1 LTS 64-bit
Gnome 42.5
Windowing System: Wayland
Browser: Chrome

![screenshot](https://i.imgur.com/phaL8Sm.png)

I checked I have the latest version of `chrome-gnome-shell`:

```bash
$ sudo apt-get install chrome-gnome-shell
...
chrome-gnome-shell is already the newest version (10.1-5).
```

The documentation also mentions a possible cause
> Problem:
> You are getting information message about missing "v6" api.
>
> Resolution:
> You need to update `gnome-browser-connector` to at least version 42.0

But I failed to install it via 
```bash
$ sudo apt-get install gnome-browser-connector
...
E: Unable to locate package gnome-browser-connector
```

**Comment by mgalgs** [comment]
You mention `chrome-gnome-shell`, but just to check, are you using Firefox? Looks like Ubuntu is shipping Firefox as a snap in 22.04 :roll_eyes:, which means it can't be used to install extensions due to sandboxing. You'll have to install your gnome shell extensions using something other than Firefox:

https://askubuntu.com/a/1406733

**Comment by maksym-arutyunyan** [comment]
No, I'm using Chrome (added to initial post).

**Comment by mgalgs** [comment]
Maybe Chrome is running as a Snap? Try installing the extension with the gnome shell extension manager (`sudo apt install gnome-shell-extension-manager`)

**Comment by maksym-arutyunyan** [comment]
I tried both Extensions and Extension Manager. It gets installed but was never activated and has some sort of an error look.

![screenshot](https://i.imgur.com/WyuygHg.png)

![screenshot](https://i.imgur.com/pgxywPL.png)

**Comment by mgalgs** [comment]
Have you restarted your session after installing? Sometimes just restarting gnome shell is enough (`alt-f2 r`)

**Comment by maksym-arutyunyan** [comment]
side note: `alt-f2 r` does not work on Wayland.

BUT! restarting the laptop actually worked! Thank you @mgalgs !
