### ISSUE TITLE
displayed memory usage is incorrect

### ISSUE THREAD

**Issue by maks** [paradoxxxzero/gnome-shell-system-monitor-applet#765]
While after a reboot it starts out displaying correct values, "after a while" the extension displays outdated memory usage, please see the screenshot comparing mem usage stats reported by the extension versus htop. Swap on the other hand does seem to be correct.

![image](https://user-images.githubusercontent.com/71999/208352909-a6c728a7-0e07-415b-86ee-0305520e135b.png)

This is on Ubuntu 22.04:
```
sb_release  -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
```

**Comment by Demetrio92** [comment]
I am pretty sure it just reports memory + cache as seen on your `htop` that does not report cached RAM as being used. 

Try `sudo sh -c 'echo 3 >/proc/sys/vm/drop_caches'` and check the numbers again

**Comment by Demetrio92** [comment]
Now try copying a large file (a few times for a good effect). You'll then see cache getting you the RAM usage increase. 

This is consistent with how `gnome-system-monitor` reports it:

![Screenshot from 2022-12-21 17-42-24](https://user-images.githubusercontent.com/22682408/208969829-362c5ff8-eab6-4847-adea-0d32ea25fb42.png)

**Comment by Demetrio92** [comment]
probably would be better for it to report it as `Used/Used+Cache/Total`, not just as `Used+Cache/Total`

**Comment by Demetrio92** [comment]
The good news is, is that if you select a graph style and hover over it, it will show both, and color-code it correctly. 
![Screenshot from 2022-12-21 17-45-46](https://user-images.githubusercontent.com/22682408/208970518-668b8ea5-82b2-4278-b83e-6607061a8261.png)

**Comment by Demetrio92** [comment]
p.s. nevermind: cannot reproduce on my fork. But your screenshot is still consistent.

**Comment by maks** [comment]
hmmm, I'm not sure if I understand this correctly.
I tried running `sudo sh -c 'echo 3 >/proc/sys/vm/drop_caches' ` but the discrepancy between what htop shows and what the extension shows remains.

The extension does show usage consistent with gnome system monitor and then checking with plain `top` gives similar usage figures, so I think this is a issue with gnome ,top reporting vs what htop shows, so I'll close this now, thanks for looking into it! 👍🏻

**Comment by Demetrio92** [comment]
In your original screenshot `htop` shows 13/30, which visually corresponds to the green bars you see. However, green bars + yellow bars together occupy roughly 70% of the width. This is your 22/30. The thing is, yellow bars are cache. 

https://www.linuxatemyram.com/

**Comment by darkxst** [comment]
This extension gets the memory stats libgtop, same as Gnome system monitor. This is where that library is calculating RAM usage. Its not simply used+cache, but probably takes into account shared memory etc as well.

```
if (server->os_version_code >= LINUX_VERSION_CODE(3, 14, 0)) {
		buf->user = buf->total - get_scaled(buffer, "MemAvailable:");
	}
```
