### ISSUE TITLE
Don't specify a lack of support for graphing usage of AMD GPUs

### ISSUE THREAD

**Issue by ZimbiX** [paradoxxxzero/gnome-shell-system-monitor-applet#769]
It looks like @D-Brox may have already [finished this in his fork](https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/compare/master...D-Brox:gnome-shell-system-monitor-applet:master)! =)

**Comment by D-Brox** [comment]
Also, my attempt didn't work like 50% of the time, it showed 0Gb of VRAM or the 3Gb it actually had

**Comment by ZimbiX** [comment]
Ah ha. Well, good effort regardless
