### ISSUE TITLE
Temperature value displays garbled

### ISSUE THREAD

**Issue by fathomrhys** [paradoxxxzero/gnome-shell-system-monitor-applet#794]
On my machine (dual UHD monitors) the temperature displays garbled as though it hasn't been cleared before writing a new number to the area. Mousing over the system monitor widget redraws it to look as it should. Unfortunately triggering a screenshot redraws it properly too!

**Comment by ZimbiX** [comment]
Resolved by https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/pull/779
